// frontend/src/routes/operaciones/productos.tsx
import { ConfirmWarn, Loading, Notify } from "~/core/main";
import { max } from "simple-statistics";
import { Show, createEffect, createMemo, createSignal } from "solid-js";
import { BarOptions, CardSelect } from "~/components/Cards";
import { CellEditable, CellTextOptions } from "~/components/Editables";
import { CheckBoxContainer, Input, refreshInput } from "~/components/Input";
import { SideLayer, openLayers, setOpenLayers } from "~/components/Modals";
import { QTable } from "~/components/QTable";
import { SearchCard, SearchSelect } from "~/components/SearchSelect";
import { throttle } from "~/core/main";
import { pageView } from "~/core/menu";
import { PageContainer } from "~/core/page";
import { IProducto, IProductoImage, IProductoPropiedad, IProductoPropiedades, postProducto, useProductosAPI } from "~/services/operaciones/productos";
import { useSedesAlmacenesAPI } from "~/services/operaciones/sedes-almacenes";
import { formatN } from "~/shared/main";
import { ImageUploader } from "~/components/Uploaders";
import { POST } from "~/shared/http";
import { useListasCompartidasAPI } from "~/services/admin/listas-compartidas";
import { ListasCompartidasLayer } from "~/routes-components/admin/listas-compartidas";
import { ProductoFichaEditor } from "~/routes-components/operaciones/productos";

export default function Productos() {

  const [almacenes] = useSedesAlmacenesAPI()
  const [listasCompartidas] = useListasCompartidasAPI([1])
  const [productos, setProductos] = useProductosAPI()

  const [filterText, setFilterText] = createSignal("")
  const [productoForm, setProductoForm] = createSignal({} as IProducto)
  const [layerView, setLayerView] = createSignal(1)
  const layerWidth = 0.48

  createEffect(() => {
    console.log("listas compartidas::",listasCompartidas())
  })

  const categorias = createMemo(() => {
    return listasCompartidas()?.Records?.filter(x => x.ListaID === 1) || []
  })
  
  const saveProducto = async (isDelete?: boolean) => {
    const form = productoForm()
    if((form.Nombre?.length||0) < 4){
      Notify.failure("El nombre debe tener al menos 4 caracteres.")
      return
    }

    Loading.standard("Creando /Actualizando Producto...")
    try {
      var result = await postProducto([form])
    } catch (error) {
      Notify.failure(error as string); Loading.remove(); return
    }

    let productos_ = [...productos().productos]

    if(form.ID){
      const selected = productos().productos.find(x => x.ID === form.ID)
      if(selected){ Object.assign(selected, form) }
      if(isDelete){ productos_ = productos_.filter(x => x.ID !== form.ID) }
    } else {
      form.ID = result[0].ID
      productos_.unshift(form)
    }
    
    setProductos({...productos(), productos: productos_})
    setProductoForm({} as IProducto)
    setOpenLayers([])
    Loading.remove()
  }
  
  const deleteProductoImage = async (ImageToDelete: string) => {
    try {
      await POST({
        data: { ProductoID: productoForm().ID, ImageToDelete },
        route: "producto-image",
        refreshIndexDBCache: "productos",
      }) 
    } catch (error) {
      Notify.failure(`Error al guardar el producto: ${error}`)
      return
    }    
    productoForm().Images = productoForm().Images.filter(e => e.n !== ImageToDelete)
    setProductoForm({...productoForm()})
  }

  let counter = -1
  
  return <PageContainer title="Productos"
    views={[[1,"Productos"],[2,"Parámetros"]]}
  >
    <Show when={pageView() === 1}>
      <div class="flex ai-center jc-between mb-06">
        <div class="search-c4 mr-16 w16rem">
          <div><i class="icon-search"></i></div>
          <input class="w100" autocomplete="off" type="text" onKeyUp={ev => {
            ev.stopPropagation()
            throttle(() => {
              setFilterText(((ev.target as any).value||"").toLowerCase().trim())
            },150)
          }}/>
        </div>
        <div class="flex ai-center">
          <button class="bn1 b-green" onClick={ev => {
            ev.stopPropagation()
            setOpenLayers([1])
            setProductoForm({ ss: 1, Propiedades: [] } as IProducto)
          }}>
            <i class="icon-plus"></i>
          </button>
        </div>
      </div>
      <QTable data={productos().productos || []} 
        css="selectable" tableCss="w-page-t"
        isSelected={(e,id) => e.ID === id as number}
        selected={productoForm().ID}
        filterText={filterText()} filterKeys={["Nombre"]}
        style={{ width: openLayers().length > 0 
          ? `calc(var(--page-width) * ${1-layerWidth})` : undefined  
        }}
        maxHeight="calc(80vh - 13rem)" 
        columns={[
          { header: "ID", headerStyle: { width: '3rem' }, css: "t-c c-purple",
            getValue: e => e.ID
          },
          { header: "Nombre", cardColumn: [3,2], field: "Nombre",
            getValue: e => e.Nombre, cardCss: "h5 c-steel",
          },
          { header: "Precio", cardColumn: [3,2], cardCss: "h5 c-steel", css: "t-c",
            getValue: e => e.Precio ? formatN(e.Precio/100,2) : "", 
          },
          { header: "Descuento", cardColumn: [3,2],  css: "t-c",
            getValue: e => e.Descuento ? formatN(e.Descuento,1) + "%" : "",
          },
          { header: "Precio Final", cardColumn: [3,2],  css: "t-c",
            getValue: e => e.PrecioFinal ? formatN(e.PrecioFinal/100,2) : "",
          },
          { header: "Sub-Unidades", cardColumn: [3,2],
            getValue: e => {
              if(!e.SbnUnidad) return ""
              return `${e.SbnCantidad} x ${e.SbnUnidad}`
            }
          },
          { header: "Grupos", cardColumn: [3,2],  css: "t-c",
            getValue: e => ""
          },
        ]}
        onRowCLick={e => {
          if(e.ID === productoForm().ID){
            setProductoForm({} as IProducto) 
            setOpenLayers([]) 
          } else {
            setProductoForm({...e})
            setOpenLayers([1]) 
          }
        }}
      />
      <SideLayer id={1} style={{ width: `calc(var(--page-width) * ${layerWidth})` }}
        title={"Producto " + (productoForm()?.Nombre||"(Nuevo)") }
        onClose={() => {
          setProductoForm({} as IProducto) 
        }}
        onSave={() => {
          saveProducto()
        }}
      >
        <div></div>
        <BarOptions selectedID={layerView()} class="w100"
          options={[[1,'Información'],[2,'Ficha'],[3,'Fotos']]}
          buttonStyle={{ "min-height": '2.1rem' }} buttonClass="ff-bold"
          onSelect={id => {
            setLayerView(id)
          }}
        />
        <Show when={layerView() === 1}>
          <div class="flex-wrap w100 mt-12">
            <Input saveOn={productoForm()} save="Nombre" required={true}
              css="w-24x mb-10" label="Nombre" 
            />
            <div class="flex-wrap ac-baseline w100 p-rel" 
                style={{ "min-height": 'calc(10rem + 10px' }}>
              <div class="w-05x p-rel">
                <ImageUploader  cardStyle={{ width: '100%', position: 'absolute', 
                  top: '0', "z-index": 12, "max-height": '10rem' }}
                  types={["avif","webp"]}
                  src={productoForm().Image
                    ? `img-productos/${productoForm().Image.n}-x2` : ""}
                />
              </div>
              <Input saveOn={productoForm()} save="Precio" id={1}
                css="w-055x mb-10" label="Precio Base" type="number"
                baseDecimals={2}
                onChange={() => {
                  const form = productoForm()
                  form.PrecioFinal = Math.floor(form.Precio * (1-(form.Descuento||0)/100))
                  refreshInput([3])
                }}
              />
              <Input saveOn={productoForm()} save="Descuento" 
                css="w-04x mb-10" label="Desc." type="number"
                postValue={<div class="p-abs pos-v c-steel1">%</div>}
                onChange={() => {
                  const form = productoForm()
                  form.PrecioFinal = Math.floor(form.Precio * (1-(form.Descuento||0)/100))
                  refreshInput([3])
                  console.log("form::", form)
                }}
              />
              <Input saveOn={productoForm()} save="PrecioFinal" id={3}
                css="w-055x mb-10" label="Precio Final" type="number"
                baseDecimals={2}
                onChange={() => {
                  const form = productoForm()
                  form.Precio = Math.floor(form.PrecioFinal / (1-(form.Descuento||0)/100))
                  refreshInput([1])
                }}
              />
              <SearchSelect saveOn={productoForm()} save="Moneda" placeholder=" "
                css="w-04x mb-10" 
                label="Moneda" keys="i.v" options={[
                  {i:1, v:"PEN (S/.)"},{i:2, v:"g"},{i:3, v:"Libras"}
                ]}
              />
              <div class="w-05x p-rel"></div>
              <Input saveOn={productoForm()} save="Peso" css="w-055x mb-10"
                label="Peso" type="number"
              />
              <SearchSelect saveOn={productoForm()} save="PesoT" placeholder=" "
                label="Un" keys="i.v" css="w-04x mb-10"
                options={[
                  {i:1, v:"Kg"},{i:2, v:"g"},{i:3, v:"Libras"}
                ]}
              />
              <Input saveOn={productoForm()} save="Volumen" css="w-055x mb-10"
                label="Volumen" type="number"
              />
              <SearchSelect saveOn={productoForm()} save="VolumenT" placeholder=" "
                label="Un" keys="i.v" css="w-04x mb-10"
                options={[
                  {i:1, v:"Kg"},{i:2, v:"g"},{i:3, v:"Libras"}
                ]}
              />
              <div class="w-24x mb-04 flex jc-end">
                <CheckBoxContainer options={[ { v: 1, n: 'SKU Individual' } ]} 
                  keys="v.n" saveOn={productoForm()} save="Params" />
              </div>
            </div>
            <div class="w100 mb-10">
              <SearchCard placeholder="CATEGORÍAS ::" options={categorias()} keys="ID.Nombre"
                css="w100 s11" saveOn={productoForm()} save="CategoriasIDs" 
                inputCss="w-06x"
              />
            </div>
            <Input saveOn={productoForm()} save="Descripcion"
              css="w-24x mb-10" label="Descripción Corta" 
            />
            <div class="ff-bold h3 mb-06">
              <div class="ml-08">Sub-Unidades</div>
            </div>
            <div class="flex w100">
              <Input saveOn={productoForm()} save="SbnUnidad" 
                css="w-05x mb-10" label="Nombre"
              />
              <Input saveOn={productoForm()} save="SbnPrecio" baseDecimals={2}
                css="w-055x mb-10" label="Precio Base" type="number"
              />
              <Input saveOn={productoForm()} save="SbnDescuento" 
                postValue={<div class="p-abs pos-v c-steel1">%</div>}
                css="w-04x mb-10" label="Descuento" type="number"
              />
              <Input saveOn={productoForm()} save="SbnPreciFinal" baseDecimals={2}
                css="w-055x mb-10" label="Precio Final" type="number"
              />
              <Input saveOn={productoForm()} save="SbnCantidad" 
                css="w-04x mb-10" label="Cantidad" type="number"
              />
            </div>
          </div>
          <div class="w100 py-04 px-04">
            <QTable data={(productoForm().Propiedades||[]).filter(x => x.Status)}
              maxHeight="40rem" tableCss="single-color"
              columns={[
                { header: "Propiedad", headerStyle: { width: '8rem' },
                  render: e => {
                    return  <CellEditable save="Nombre" saveOn={e} 
                      contentClass="flex ai-center nowrap" required={true} />
                  }
                },
                { header: "Opciones", cardColumn: [3,2],
                  render: e => {
                    return <CellTextOptions saveOn={e} save="Options" 
                      getValue={(e: IProductoPropiedad) => e.nm}
                      skipt={e => !e.ss}
                      setValue={(e,content) => {
                        e.nm = content
                        e.ss = 1
                        if(!e.id){ e.id = counter; counter-- }
                        return e
                      }}
                    />
                  }
                },
                { header: <div>
                    <button class="bn1 s2 b-green" onclick={ev => {
                      ev.stopPropagation()
                      const propiedades = [...productoForm().Propiedades]
                      const id = propiedades.length > 0 ? max(propiedades.map(x => x.ID)) : 0
                      propiedades.push({ ID: id + 1, Status: 1, Options: [] } as IProductoPropiedades)
                      productoForm().Propiedades = propiedades
                      setProductoForm({...productoForm()})
                    }}>
                      <i class="icon-plus"></i>
                    </button>
                  </div>, 
                  headerStyle: { width: '2.6rem' }, css: "t-c",
                  cardColumn: [1,2],
                  render: e => {
                    return <button class="bnr2 b-red b-card-1" onClick={ev => {
                      ev.stopPropagation()
                      const propiedades = productoForm().Propiedades.filter(x => x !== e)
                      productoForm().Propiedades = propiedades
                      setProductoForm({...productoForm()})
                    }}>
                      <i class="icon-trash"></i>
                    </button>
                  }
                }
              ]}    
            />
          </div>
        </Show>
        <Show when={layerView() === 2}>
          <ProductoFichaEditor producto={productoForm()} />
        </Show>
        <Show when={layerView() === 3}>
          <div class="w100 px-02 py-08"
            style={{ display: 'grid', 
              'grid-template-columns': '1fr 1fr 1fr 1fr', 'grid-gap': '8px' }}
          >
            <ImageUploader saveAPI="producto-image"
              refreshIndexDBCache="productos"
              clearOnUpload={true}
              cardStyle={{ width: '100%' }}
              setDataToSend={e => {
                e.ProductoID = productoForm().ID
              }}
              onUploaded={src => {
                const name = src.split("/")[1]
                const images = productoForm().Images || []
                images.push({ n: name } as IProductoImage)
                productoForm().Images = images
                setProductoForm({...productoForm()})
              }}
            />
            { (productoForm().Images||[]).map(e => {
                return <ImageUploader src={"img-productos/"+ e.n + "-x2"}
                  cardStyle={{ width: '100%' }}
                  types={["avif","webp"]} 
                  onDelete={() => {
                    ConfirmWarn("ELIMINAR IMAGEN",
                      `Eliminar la imagen ${e.d ? `"${e.d}"` : "seleccionada"}`,
                      "SI","NO",
                      () => {
                        deleteProductoImage(e.n)
                      }
                    )
                  }}  
                />
              })
            }
          </div>
        </Show>
      </SideLayer>
    </Show>
    <Show when={pageView() === 2}>
      <div class="flex ai-center jc-between mb-06">
        <ListasCompartidasLayer listaID={1} listas={listasCompartidas()} />
      </div>
    </Show>
  </PageContainer>
}

// frontend2/src/routes/operaciones/productos/+page.svelte
<script lang="ts">
    import CheckboxOptions from "$components/CheckboxOptions.svelte";
    import Input from "$components/Input.svelte";
    import HTMLEditor from "$components/micro/HTMLEditor.svelte";
    import { ConfirmWarn, Loading, Notify } from "$lib/helpers";
    import { POST } from "$lib/http";
    import ImageUploader from "../../../components/ImageUploader.svelte";
    import Layer from "../../../components/Layer.svelte";
    import OptionsStrip from "../../../components/micro/OptionsStrip.svelte";
    import Page from "$components/Page.svelte";
    import SearchCard from "../../../components/SearchCard.svelte";
    import SearchSelect from "../../../components/SearchSelect.svelte";
    import type { ITableColumn } from "../../../components/VTable";
    import VTable from "../../../components/VTable/vTable.svelte";
    import { throttle } from "../../../core/helpers";
    import { Core } from "../../../core/store.svelte";
    import { formatN } from "../../../shared/main";
    import Atributos from "./Atributos.svelte";
    import CategoriasMarcas from "./CategoriasMarcas.svelte";
    import { ListasCompartidasService, postProducto, productoAtributos, ProductosService, type IProducto, type IProductoImage } from "./productos.svelte";

  let filterText = $state("")
  const productos = new ProductosService()
  const listas = new ListasCompartidasService([1,2])

  let view = $state(1)
  let layerView = $state(1)
  let productoForm = $state({} as IProducto)
  // svelte-ignore non_reactive_update
  let CategoriasLayer: CategoriasMarcas | null = null
  // svelte-ignore non_reactive_update
  let MarcasLayer: CategoriasMarcas | null = null

  let productoColumns: ITableColumn<IProducto>[] = [
    { header: "ID", css: "c-blue text-center", headerCss: "w-48",
      getValue: e => e.ID
    },
    { header: "Producto", highlight: true,
      getValue: e => e.Nombre
    },
    { header: "Categorías", highlight: true,
      getValue: e => {
        const nombres = []
        for(const id of e.CategoriasIDs){
          const nombre = listas.get(id)?.Nombre || `Categoría-${id}`
          nombres.push(nombre)
        }
        return nombres.join(", ")
      }
    },
    { header: "Precio", css: "text-right",
      getValue: e => formatN(e.Precio / 100,2)
    },
    { header: "Descuento", css: "text-right",
      getValue: e => e.Descuento ? String(e.Descuento) + "%" : ""
    },
    { header: "Precio Final", css: "text-right",
      getValue: e => formatN(e.PrecioFinal / 100,2)
    },
    { header: "Sub Unidades", css: "text-right",
      getValue: e => {
        if(!e.SbnUnidad) return ""
        return `${e.SbnCantidad} x ${e.SbnUnidad}`
      }
    },
  ]

  const categorias = $derived.by(() => {
    return listas.ListaRecordsMap.get(1) || []
  })

  const onSave = async (isDelete?: boolean) => {
    if((productoForm.Nombre?.length||0) < 4){
      Notify.failure("El nombre debe tener al menos 4 caracteres.")
      return
    }

    console.log("productor a enviar:",$state.snapshot(productoForm))
    // return

    Loading.standard("Guardando producto...")
    try {
      var productosUpdated = await postProducto([productoForm])
    } catch (error) {
      Notify.failure(error as string); Loading.remove(); return
    }
    Loading.remove()

    const producto = productos.productos.find(x => x.ID === productoForm.ID)
    if(producto && isDelete){
      productos.productos = productos.productos.filter(x => x.ID !== productoForm.ID)
    } else if(producto) {
      Object.assign(producto, productoForm)
    } else {
      productoForm.ID = productosUpdated[0].ID
      productos.productos.unshift(productoForm)
      productos.productos = [...productos.productos]
    }
    Core.openSideLayer(0)
  }

  $effect(() => {
    console.log("productor form:", $state.snapshot(productoForm))
  })

  const deleteProductoImage = async (ImageToDelete: string) => {
    Loading.standard("Eliminando Imagen...")
    try {
      await POST({
        data: { ProductoID: productoForm.ID, ImageToDelete },
        route: "producto-image",
        refreshRoutes: ["productos"],
      }) 
    } catch (error) {
      Notify.failure(`Error al eliminar imagen: ${error}`)
      Loading.remove()
      return
    }    
    Loading.remove()
    productoForm.Images = (productoForm.Images||[]).filter(e => e.n !== ImageToDelete)
  }

</script>

<Page sideLayerSize={780} title="Productos" >
  <div class="grid grid-cols-12 md:flex md:flex-row items-center mb-8">
    <OptionsStrip selected={view} css="col-span-12 mb-6 md:mb-0"
      options={[[1,"Productos"],[2,"Categorías"],[3,"Marcas"]]} 
      useMobileGrid={true}
      onSelect={e => {
        Core.openSideLayer(0)
        productoForm = { ID: 0 } as IProducto
        view = e[0] as number
      }}
    />
    <div class="i-search w-full md:w-200 md:ml-12 col-span-5">
      <div><i class="icon-search"></i></div>
      <input type="text" onkeyup={ev => {
        const value = String((ev.target as any).value||"")
        throttle(() => { filterText = value },150)
      }}>
    </div>

    <button class="bx-green ml-auto col-span-7" onclick={ev => {
      ev.stopPropagation()
      if(view === 2){
        CategoriasLayer?.newRecord()
      } else if(view === 3) {
        MarcasLayer?.newRecord()
      } else {
        Core.openSideLayer(1)
      }
    }}>
      <i class="icon-plus"></i><span class="hidden md:block">Nuevo</span>
    </button>
  </div>

  {#if view === 1}
    <Layer type="content">
      <VTable columns={productoColumns}
        data={productos.productos}
        filterText={filterText}
        selected={productoForm?.ID}
        isSelected={(e,id) => e.ID === id}
        getFilterContent={e => {
          return e.Nombre
        }}
        onRowClick={e => {
          productoForm = {...e}
          productoForm.CategoriasIDs = [...(e.CategoriasIDs||[])]
          productoForm.Propiedades = [...(e.Propiedades||[])]
          Core.openSideLayer(1)
        }}
      />
    </Layer>
  {/if}
  <Layer type="side" css="px-8 py-8 md:px-14 md:py-10" 
    title={productoForm?.Nombre || ""} 
    titleCss="h2 mb-6" contentCss="px-0 md:px-0" id={1}
    bind:selected={layerView}
    onClose={() => { productoForm = {} as IProducto }}
    onSave={() => { onSave() }}
    onDelete={() => { 
      ConfirmWarn("Eliminar Producto",
        `¿Está seguro que desea eliminar "${productoForm.Nombre}"?`,
        "SI", "NO", () => { onSave(true) }
      )
    }}
    options={[
      [1,"Información",["Informa-","ción"]],
      [2,"Ficha"],
      [3,"Presentaciones",["Presenta-","ciones"]],
      [4,"Fotos"]
    ]}
  >
    {#if layerView === 1}
      <div class="grid grid-cols-24 items-start gap-x-10 gap-y-10 mt-6 md:mt-16">
        <Input label="Nombre" saveOn={productoForm} css="col-span-24"
          required={true} save="Nombre"
        />
        <div class="col-span-24 md:col-span-9 md:row-span-4">
          <ImageUploader saveAPI="producto-image" useConvertAvif={true}
            clearOnUpload={true} types={["avif","webp"]}
            folder="img-productos" size={2} src={productoForm.Image?.n}
            cardCss="w-full h-180 p-4"
            setDataToSend={e => {
              e.ProductoID = productoForm.ID
            }}
            onUploaded={(imagePath, description) => {
              if(imagePath.includes("/")){ imagePath = imagePath.split("/")[1] }
              productoForm.Image = { n: imagePath, d: description } as IProductoImage
              productoForm.Images = productoForm.Images || []
              productoForm.Images.unshift(productoForm.Image)
            }}
          />
        </div>
        <Input label="Precio Base" saveOn={productoForm} 
          css="col-span-12 md:col-span-5"
          save="Precio" type="number" baseDecimals={2}
          dependencyValue={productoForm.Precio}
          onChange={() => {
            console.log("productoForm", $state.snapshot(productoForm))
            productoForm.PrecioFinal = Math.round((productoForm.Precio * (100 - (productoForm.Descuento||0))) / 100)
          }}
        />
        <Input label="Descuento" saveOn={productoForm} 
          css="col-span-12 md:col-span-5"
          save="Descuento" postValue="%" type="number"
          validator={v => { return !v || v as number < 100 }}
        />
        <Input label="Precio Final" saveOn={productoForm} 
          css="col-span-12 md:col-span-5"
          dependencyValue={productoForm.PrecioFinal}
          save="PrecioFinal" type="number" baseDecimals={2}
          onChange={() => {
            console.log("productoForm", $state.snapshot(productoForm))
            productoForm.Precio = Math.round((productoForm.PrecioFinal / (100 - (productoForm.Descuento||0))) * 100)
          }}
        />
        <SearchSelect label="Moneda" saveOn={productoForm} 
          css="col-span-12 md:col-span-5"
          save="MonedaID" keyId="i" keyName="v"
          options={[
            {i:1, v:"PEN (S/.)"},{i:2, v:"USD ($)"}
          ]}
        />
        <Input label="Peso" saveOn={productoForm} css="col-span-12 md:col-span-5"
          save="Peso" type="number"
        />
        <SearchSelect label="Unidad" saveOn={productoForm} css="col-span-12 md:col-span-5"
          save="UnidadID" keyId="i" keyName="v"
          options={[
            {i:1, v:"Kg"},{i:2, v:"g"},{i:3, v:"Libras"}
          ]}
        />
        <Input label="Volumen" saveOn={productoForm} css="col-span-12 md:col-span-5"
          save="Volumen" type="number"
        />
        <SearchSelect label="Marca" saveOn={productoForm} css="col-span-12 md:col-span-10 mb-2"
          save="MarcaID" keyId="ID" keyName="Nombre"
          options={listas.ListaRecordsMap.get(2)||[]}
        />
        <div class="col-span-24 md:col-span-14">
          <CheckboxOptions save="Params" saveOn={productoForm} type="multiple"
            options={[{i:1, v:"SKU Individual"}]} keyId="i" keyName="v"
          />
        </div>
        <Input saveOn={productoForm} save="Descripcion"
          css="col-span-24 mb-4" label="Descripción Corta" 
        />
        <SearchCard css="col-span-24 flex items-start" label="CATEGORÍAS ::"
          options={categorias} keyId="ID" keyName="Nombre"
          cardCss="grow" inputCss="w-[35%] md:w-180" bind:saveOn={productoForm}
          save="CategoriasIDs" optionsCss="w-280"
        />
        <div class="ff-bold h3 col-span-24 ml-8">
          Sub-Unidades
        </div>
        <Input saveOn={productoForm} save="SbnUnidad" 
          css="col-span-12 md:col-span-6" label="Nombre"
        />
        <Input bind:saveOn={productoForm} save="SbnPrecio" baseDecimals={2}
          css="col-span-12 md:col-span-6" label="Precio Base" type="number"
          onChange={() => {
            console.log()
            productoForm.PrecioFinal = Math.round((productoForm.Precio * (100 - (productoForm.Descuento||0))) / 100)
            productoForm = {...productoForm}
          }}
        />
        <Input saveOn={productoForm} save="SbnDescuento" postValue="%"
          css="col-span-12 md:col-span-6" label="Descuento" type="number"
        />
        <Input saveOn={productoForm} save="SbnPreciFinal" baseDecimals={2}
          css="col-span-12 md:col-span-6" label="Precio Final" type="number"
        />
        <Input saveOn={productoForm} save="SbnCantidad" 
          css="col-span-12 md:col-span-6" label="Cantidad" type="number"
        />
      </div>
    {/if}
    {#if layerView === 2}
      <HTMLEditor saveOn={productoForm} save="ContentHTML" 
        css="mt-12"/>
    {/if}
    {#if layerView === 3}
      <div class="mt-16 w-full">
        <Atributos bind:producto={productoForm}></Atributos>
      </div>
    {/if}
    {#if layerView === 4}
      <div class="grid grid-cols-2 md:grid-cols-4 items-start gap-x-10 gap-y-10 mt-16">
        <ImageUploader saveAPI="producto-image" useConvertAvif={true}
          clearOnUpload={true} types={["avif","webp"]} folder="img-productos"
          cardCss="w-full h-170 p-4"
          setDataToSend={e => {
            e.ProductoID = productoForm.ID
          }}
          onUploaded={(imagePath, description) => {
            if(imagePath.includes("/")){ imagePath = imagePath.split("/")[1] }
            productoForm.Image = { n: imagePath, d: description } as IProductoImage
            productoForm.Images = productoForm.Images || []
            productoForm.Images.unshift(productoForm.Image)
          }}
        />
        {#each (productoForm.Images||[]) as image }
          <ImageUploader saveAPI="producto-image" size={2}
            clearOnUpload={true} types={["avif","webp"]} folder="img-productos"
            cardCss="w-full h-170 p-4" src={image?.n} useConvertAvif={true}
            onDelete={() => {
              ConfirmWarn("ELIMINAR IMAGEN",
                `Eliminar la imagen ${image.d ? `"${image.d}"` : "seleccionada"}`,
                "SI","NO",
                () => {
                  deleteProductoImage(image.n)
                }
              )
            }}
          />
        {/each}
      </div>
    {/if}
  </Layer>
  {#if view === 2}
    <CategoriasMarcas listas={listas} origin={1} bind:this={CategoriasLayer}/>
  {/if}
  {#if view === 3}
    <CategoriasMarcas listas={listas} origin={2} bind:this={MarcasLayer}/>
  {/if}
</Page>
