// frontend2/src/routes/operaciones/productos-stock/+page.svelte
<script lang="ts">
    import Page from "$components/Page.svelte";
    import SearchSelect from "$components/SearchSelect.svelte";
    import type { ITableColumn } from "$components/VTable";
    import VTable from "$components/VTable/vTable.svelte";
    import { Notify, throttle } from "$lib/helpers";
    import { Loading } from "notiflix";
    import { ProductosService } from "../productos/productos.svelte";
    import { AlmacenesService } from "../sedes-almacenes/sedes-almacenes.svelte";
    import { getProductosStock, postProductosStock, type IProductoStock } from "./productos-stock.svelte";
    import { Core } from "$core/store.svelte";
    import Layer from "$components/Layer.svelte";
    import Input from "$components/Input.svelte";
    import Checkbox from "$components/Checkbox.svelte";
    import { untrack } from "svelte";

  const almacenes = new AlmacenesService()
  const productos = new ProductosService()

  let filters = $state({ almacenID: 0, showTodosProductos: false })
  let filterText = $state("")
  let almacenStock = $state([] as IProductoStock[])
  let almacenStockGetted = [] as IProductoStock[]
  let form = $state({} as IProductoStock)

  let formProducto = $derived(productos?.productosMap?.get(form.ProductoID||0))

  $effect(() => {
    if(!filters.almacenID){ return }
  })

  let columns: ITableColumn<IProductoStock>[] = [
    { header: "Producto", highlight: true,
      getValue: e => {
        const producto = productos.productosMap.get(e.ProductoID)?.Nombre
        return producto || ""
      }
    },
    { header: "Lote",
      getValue: e => e.Lote || ""
    },
    { header: "SKU",
      getValue: e => e.SKU || ""
    },    
    { header: "Presentación",
      getValue: e => {
        if(!e.PresentacionID){ return "" }
        const producto = productos.productosMap.get(e.ProductoID)
        const pr = producto?.Presentaciones?.find(x => x.id === e.PresentacionID)
        return pr?.nm || ""
      }
    },
    { header: "Stock",
      getValue: e => e.Cantidad,
      onCellEdit: (e, value) => {
        agregarStock(e, parseInt(value as string||"0"))
      },
      render: e => {
        if(e._cantidadPrev && e._cantidadPrev !== e.Cantidad){
          return {
            css: "flex items-center",
            children: [
              { text: String(e._cantidadPrev > 0 ?  e._cantidadPrev : 0) },
              { text: "→", css: "ml-2 mr-2"  },
              { text: e.Cantidad, css: "c-red"  }
            ]
          }          
        } else {
          return { text: e.Cantidad || ""  }
        }
      }
    },
    { header: "Costo Un.",
      onCellEdit: (e, value) => {
        e._hasUpdated = true
        e.CostoUn = parseInt(value as string||"0")
      },
    },
  ]

  const onChangeAlmacen = async () => {
    if(!filters.almacenID){ return }
    Loading.standard()
    try {
      var result = await getProductosStock(filters.almacenID)
    } catch (error) {
      Loading.remove()
      return
    }
    Loading.remove()
    almacenStock = result || []
    almacenStockGetted = result || []
  }

  const guardarRegistros = async () => {
    const recordsForUpdate = almacenStock.filter(e => e._hasUpdated)
    if(recordsForUpdate.length === 0){
      Notify.failure("No hay registros a actualizar."); return
    }

    Loading.standard("Enviando registros...")
    let result
    try {
      result = await postProductosStock(recordsForUpdate)
    } catch (error) {
      Loading.remove(); return
    }

    for(const e of almacenStock){
      e._cantidadPrev = 0
    }
    console.log("resultado obtenido::", result)
    // setProductosStock([...productosStock()])
    Loading.remove()
  }

  const fillAllProductos = () => {
    console.log("almacenStockGetted", $state.snapshot(almacenStockGetted))

    const productosStockMap = new Map(almacenStockGetted?.map(x => [x.ID, x]))
    for(const pr of productos.productos){
      const presentacionesIDs = pr.Presentaciones?.length > 0 ? pr.Presentaciones.map(x => x.id) : [0]
      for(const presentacionID of presentacionesIDs){
        const stockID = [filters.almacenID, pr.ID, presentacionID || "", "", ""].join("_")
        if(productosStockMap.has(stockID)){ 
          const e = productosStockMap.get(stockID) as IProductoStock
          e.PresentacionID = presentacionID
          continue 
        }

        const stock = {
          ID: stockID,
          AlmacenID: filters.almacenID,
          ProductoID: pr.ID,
          PresentacionID: presentacionID,
          Cantidad: 0
        } as IProductoStock
        productosStockMap.set(stockID, stock)
      }
    }
    almacenStock = [...productosStockMap.values()]
  }

  const agregarStock = (e: IProductoStock, cantidad: number) => {
    if(!e.ID){
      e.ID = [
        e.AlmacenID, e.ProductoID, e.PresentacionID||0, e.SKU||"", e.Lote||""
      ].join("_")
    }

    const base = almacenStock.find(x => x.ID === e.ID) || almacenStockGetted.find(x => x.ID === e.ID)

    if(base){
      base._hasUpdated = true
      base._cantidadPrev = base._cantidadPrev || base.Cantidad || -1
      base.Cantidad = cantidad
    } else {
      e._cantidadPrev = -1
      e._hasUpdated = true
      almacenStockGetted.unshift(e)
      almacenStock.unshift(e)
      almacenStock = [...almacenStock]
    }
  }

  $effect(() => {
    if(filters.showTodosProductos){
      untrack(() => { fillAllProductos() })
    } else {
      untrack(() => { almacenStock = almacenStockGetted })
    }
  })

</script>

<Page sideLayerSize={640} title="productos-stock">
  <div class="flex items-center mb-8">
    <SearchSelect options={almacenes?.Almacenes||[]} keyId="ID" keyName="Nombre" 
      saveOn={filters} save="almacenID" placeholder="ALMACÉN ::"
      css="w-270"
      onChange={() => {
        onChangeAlmacen()
      }}
    />
    {#if !filters.almacenID}
      <div class="ml-12 c-red"><i class="icon-attention"></i>Debe seleccionar un almacén.</div>
    {:else}
      <div class="i-search w-full md:w-200 md:ml-12 col-span-5">
        <div><i class="icon-search"></i></div>
        <input type="text" onkeyup={ev => {
          const value = String((ev.target as any).value||"")
          throttle(() => { filterText = value },150)
        }}>
      </div>
      <Checkbox label="Todos los Productos" saveOn={filters} save="showTodosProductos" 
        css="ml-16" />
    {/if}
    <div class="ml-auto">
      {#if filters.almacenID > 0}
        <button class="bx-blue mr-8" onclick={() => {
          guardarRegistros()
        }}>
          <i class="icon-floppy"></i>Guardar
        </button>
        <button class="bx-green" aria-label="agregar" onclick={() => {
          form = { AlmacenID: filters.almacenID } as IProductoStock
          Core.openSideLayer(1)
        }}>
          <i class="icon-plus"></i>
        </button>
      {/if}
    </div>
  </div>
  <VTable columns={columns} data={almacenStock}
    filterText={filterText}
    useFilterCache={true}
    getFilterContent={e => {
      const producto = productos.productosMap.get(e.ProductoID)
      return [producto?.Nombre, e.SKU, e.Lote].filter(x => x).join(" ").toLowerCase()
    }}
  >

  </VTable>
  <Layer id={1} type="bottom" css="p-12 min-h-360" title="Agregar Stock" titleCss="h2"
    saveButtonName="Agregar" saveButtonIcon="icon-ok" contentOverflow={true}
    onSave={() => {
      if(!form.ProductoID || !form.Cantidad){
        Notify.failure("Debe seleccionar un producto y una cantidad.")
      }
      agregarStock(form, form.Cantidad)
      // almacenStock = [...almacenStock]
      Core.hideSideLayer()
    }}
  >
    <div class="grid grid-cols-24 gap-10 mt-6 p-4">
      <SearchSelect label="Producto" css="col-span-24" required={true}
        saveOn={form} save="ProductoID" options={productos.productos||[]}
        keyName="Nombre" keyId="ID"
      />
      {#if (formProducto?.Presentaciones?.filter(x => x.ss)||[]).length > 0}
        <SearchSelect label="Presentación" css="col-span-24"
          saveOn={form} save="PresentacionID" options={formProducto?.Presentaciones||[]}
          keyName="nm" keyId="id"
        />
      {/if}
      <Input label="SKU" css="col-span-16"
        saveOn={form} save="SKU"
      />
      <Input label="Cantidad" required={true} css="col-span-8"
        saveOn={form} save="Cantidad" type="number"
      />
      <Input label="Lote" css="col-span-16"
        saveOn={form} save="Lote"
      />
      <Input label="Costo x Unidad" css="col-span-8"
        saveOn={form} save="CostoUn" type="number"
      />
    </div>
  </Layer>
</Page>

// frontend/src/routes/operaciones/productos-stock.tsx
import { Notify } from "notiflix"
import { Show, createSignal } from "solid-js"
import { CellEditable } from "~/components/Editables"
import { CheckBox, Input } from "~/components/Input"
import { CornerLayer, setOpenLayers } from "~/components/Modals"
import { QTable } from "~/components/QTable"
import { SearchSelect } from "~/components/SearchSelect"
import { Loading, throttle } from "~/core/main"
import { PageContainer } from "~/core/page"
import { IProductoStock, getProductosStock, postProductosStock, useProductosAPI } from "~/services/operaciones/productos"
import { useSedesAlmacenesAPI } from "~/services/operaciones/sedes-almacenes"
import { formatN } from "~/shared/main"

export default function ProductosStock() {

  const [productosStock, setProductosStock] = createSignal([] as IProductoStock[])
  const [productos] = useProductosAPI()
  const [almacenes] = useSedesAlmacenesAPI()
  const [form, setForm] = createSignal({})
  const [formStock, setFormStock] = createSignal({} as IProductoStock)
  const [almacenSelected, setAlmacenSelected] = createSignal(0)
  const [keysUpdated, setKeysUpdated] = createSignal(new Set() as Set<string>)
  const [todosProductosCheck, setTodosProductosCheck] = createSignal(false)

  let productoStockMap: Map<string,IProductoStock> = new Map()

  const getStock = async (almacenID: number) => {
    let stock: IProductoStock[] = []
    Loading.standard("Obteniendo Registros...")
    try {
      stock = await getProductosStock(almacenID) 
    } catch (error) {
      Loading.remove(); return
    }
    console.log("productos stock::", stock)
    setProductosStock(stock)

    for(let e of stock){
      const key = [e.ProductoID,e.SKU||"0",e.Lote||"0"].join("_")
      productoStockMap.set(key,e)
    }
    Loading.remove(); return
  }

  const addProductoStock = (rec: IProductoStock) => {
    if(!rec.ProductoID || !rec.Cantidad){
      Notify.failure("Debe seleccionar un producto y asignar una cantidad.")
      return
    }
    const key = [rec.ProductoID,rec.SKU||"0",rec.Lote||"0"].join("_")
    const currentStock = productosStock()
    keysUpdated().add(key)

    if(productoStockMap.has(key)){
      const current = productoStockMap.get(key)
      current.Cantidad = rec.Cantidad
      current.CostoUn = rec.CostoUn || current.CostoUn
      current._cantidadPrev = current._cantidadPrev || current.Cantidad || -1
      current._hasUpdated = true
    } else {
      productoStockMap.set(key, rec)
      currentStock.unshift(rec)
      rec._cantidadPrev = -1
      rec.AlmacenID = almacenSelected()
      rec._hasUpdated = true
    }
    setKeysUpdated(new Set(keysUpdated()))
    setProductosStock([...currentStock])
    setFormStock({} as IProductoStock)
  }

  const guardarRegistros = async () => {
    const recordsForUpdate = productosStock().filter(e => e._hasUpdated)
    if(recordsForUpdate.length === 0){
      Notify.failure("No hay registros a actualizar."); return
    }

    Loading.standard("Enviando registros...")
    let result
    try {
      result = await postProductosStock(recordsForUpdate)
    } catch (error) {
      Loading.remove(); return
    }

    for(let e of recordsForUpdate){
      e._cantidadPrev = 0
    }
    console.log("resultado obtenido::", result)
    setProductosStock([...productosStock()])
    Loading.remove()
  }

  const [filterText, setFilterText] = createSignal("")

  const populateProductos = (productosStock: IProductoStock[], almacenID: number) => {
    const usedProductosIDSet = new Set(productosStock.map(x => x.ProductoID))
    const newProductosStock = [...productosStock]

    for(let producto of productos().productos){
      if(usedProductosIDSet.has(producto.ID)){ continue }
      newProductosStock.push({
        AlmacenID: almacenID,
        ProductoID: producto.ID,
        Cantidad: 0,
        _isVirtual: true
      } as IProductoStock)
    }
    return newProductosStock
  }

  return <PageContainer title="Almacén Stock">
    <div class="flex ai-center jc-between mb-06">
      <div class="flex ai-center">
        <SearchSelect saveOn={form()} save="almacenID" css="w20rem s6 mb-02 mr-12"
          label="" keys="ID.Nombre" options={almacenes()?.Almacenes || []}
          placeholder=" ALMACÉN"
          onChange={e => {
            setAlmacenSelected(e?.ID||0)
            if(e){ getStock(e.ID); return }
          }}
        />
        <Show when={almacenSelected() > 0}>
          <div class="search-c4 mr-16 w14rem">
            <div><i class="icon-search"></i></div>
            <input class="w100" autocomplete="off" type="text" onKeyUp={ev => {
              ev.stopPropagation()
              throttle(() => {
                setFilterText(((ev.target as any).value||"").toLowerCase().trim())
              },150)
            }}/>
          </div>
          <CheckBox label="Todos Productos" checked={todosProductosCheck()}
            onChange={bool =>{
              setTodosProductosCheck(bool)
              let records = []
              if(bool){
                records = populateProductos(productosStock(), almacenSelected())
              } else {
                records = productosStock().filter(x => !x._isVirtual)
              }
              setProductosStock(records)
            }}
          />
        </Show>
        <Show when={!almacenSelected()}>
          <div class="flex ai-center c-red"> 
            <i class="icon-attention"></i> 
            Debe seleccionar un almacén.
          </div>
        </Show>
      </div>
      <div class="flex ai-center">
        <Show when={keysUpdated().size > 0}>
          <button class="bn1 b-blue mr-08" onClick={ev => {
            ev.stopPropagation()
            guardarRegistros()
          }}>
            <i class="icon-floppy"></i>
            Guardar ({keysUpdated().size})
          </button>
        </Show>
        <button class="bn1 b-green" onClick={ev => {
          ev.stopPropagation()
          setOpenLayers([2])
        }}>
          <i class="icon-plus"></i>
        </button>
      </div>
    </div>
    <QTable data={productosStock()} 
      css="" tableCss="w-page"
      maxHeight="calc(80vh - 13rem)" 
      columns={[
        { header: "Producto", css: "",
          getValue: e => {
            const producto = productos().productosMap.get(e.ProductoID)
            return producto?.Nombre || `Producto-${e.ProductoID}`
          }
        },
        { header: "Lote", css: "c-purple",
          getValue: e => e.Lote
        },
        { header: "SKU", css: "c-purple",
          getValue: e => e.SKU
        },
        { header: "Propiedades", css: "",
          getValue: e => ""
        },
        { header: "Stock", cardColumn: [3,2], field: "Nombre",
          css: "t-r", headerStyle: { width: '8rem' },
          render: e => {
            return <CellEditable saveOn={e} save="" 
              contentClass="px-06 flex ai-center jc-end"
              inputClass="t-c" type="number"
              onChange={c => {
                if(e.Cantidad === c){ return }
                e._cantidadPrev = e._cantidadPrev || e.Cantidad || -1
                e.Cantidad = parseInt(c as string||"0")
                const key = [e.ProductoID,e.SKU||"0",e.Lote||"0"].join("_")
                keysUpdated().add(key)
                setKeysUpdated(new Set(keysUpdated()))
              }}
              render={() => {
                if(e._cantidadPrev && e._cantidadPrev !== e.Cantidad){
                  const prev = e._cantidadPrev === -1 ? 0 : e._cantidadPrev
                  return <div class="flex ai-center jc-end">
                    <div>{prev}</div>
                    <div class="mr-02 ml-02">→</div>
                    <div class="c-red ff-bold">{e.Cantidad}</div>
                  </div>
                } else {
                  if(!e.Cantidad){
                    return <div class="c-red ff-bold">{e.Cantidad}</div>
                  }
                  return String(e.Cantidad)
                }
              }}
            />
          },
        },
        { header: "Costo UN", cardColumn: [3,2], cardCss: "h5 c-steel", css: "t-c",
          getValue: e => e.CostoUn ? formatN(e.CostoUn,2) : "", 
          render: e => {
            return <CellEditable saveOn={e} save="CostoUn" 
              contentClass="px-06 flex ai-center jc-end"
              inputClass="t-c" type="number"
              onChange={c => {
                e._hasUpdated = true
                const key = [e.ProductoID,e.SKU||"0",e.Lote||"0"].join("_")
                keysUpdated().add(key)
                setKeysUpdated(new Set(keysUpdated()))                
              }}
              render={() => {
                return e.CostoUn ? formatN(e.CostoUn,2) : ""
              }}
            />
          },
        },
        { header: "Stock Min", cardColumn: [3,2], cardCss: "h5 c-steel", css: "t-c",
          getValue: e => "", 
        },
      ]}
    />
    <CornerLayer title="Nuevo Producto Stock" id={2} css="py-12 px-12"
      buttonSave={<><i class="icon-ok"></i>Agregar</>}
      onSave={() => {
        addProductoStock(formStock())
      }}
    >
      <div class="w100-10 flex-wrap in-s2">        
        <SearchSelect saveOn={formStock()} save="ProductoID" css="w-24x mb-10"
          label="Producto1" keys="ID.Nombre" options={productos()?.productos || []}
          placeholder=" " required={true}
        />
        <Input saveOn={formStock()} save="SKU" 
          css="w-16x mb-10" label="SKU"
        />
        <Input saveOn={formStock()} save="Cantidad" required={true}
          css="w-08x mb-10" label="Cantidad" type="number"
        />
        <Input saveOn={formStock()} save="Lote"
          css="w-16x mb-10" label="Lote" type="text"
        />
        <Input saveOn={formStock()} save="CostoUn"
          css="w-08x mb-10" label="Costo x Unidad" type="number"
        />
      </div>
    </CornerLayer>
  </PageContainer>
}
