// frontend/src/routes/admin/parametros.tsx
import { createSignal } from "solid-js"
import { Input } from "~/components/Input"
import { PageContainer } from "~/core/page"
import { postEmpresaParametros, useEmpresasAPI, useParametrosEmpresaAPI } from "~/services/admin/empresas"
import css from "../../css/layout.module.css"
import { Loading, Notify } from "notiflix"

export default function AdminParametros() {

  const [empresa, setEmpresa] = useParametrosEmpresaAPI()

  console.log("empresa:", empresa())
  
  const saveEmpresa = async () => {
    const form = empresa()
    if((form.ruc||"").length === 0 || (form.nombre||"").length === 0 || 
      (form.razonSocial||"").length === 0 || (form.email||"").length === 0 ){
      Notify.failure("Faltan datos a guardar.")
      return
    }

    Loading.standard("Guardando registros...")
    try {
      postEmpresaParametros(form)
    } catch (error) {
      console.warn(error); return
    }
    Loading.remove()
  }

  return <PageContainer title="Parámetros" fetchLoading={true}>
    <div class="flex jc-between ai-center mb-08">
      <div><div class="h3 ff-bold">Parámetros de la Empresa</div></div>
      <div class="flex ai-center">
        <button class="bn1 b-blue" onclick={ev => {
          ev.stopPropagation()
          saveEmpresa()
        }}>
          <i class="icon-floppy"></i>
          Guardar
        </button>
      </div>
    </div>
    <div class="w100 grid" style={{ "grid-template-columns": "4fr 3fr" }}>
      <div class="flex-wrap w100-10">
        <Input css="w-14x mb-10" label="Nombre" save="nombre" saveOn={empresa()}
          required={true} />
        <Input css="w-10x mb-10" label="RUC" save="ruc" saveOn={empresa()} 
          required={true} />
        <Input css="w-14x mb-10" label="Razón Social" save="razonSocial" 
          saveOn={empresa()} required={true} />
        <Input css="w-10x mb-10" label="Teléfono" save="telefono" saveOn={empresa()} />
        <Input css="w-14x mb-10" label="Correo Electrónico" save="email" 
          saveOn={empresa()} required={true} />
        <Input css="w-10x mb-10" label="Representante" save="representante" saveOn={empresa()} />
        <Input css="w-14x mb-10" label="Dirección Legal" save="direccion" 
          saveOn={empresa()} />
        <Input css="w-10x mb-10" label="Ciudad" save="ciudad" saveOn={empresa()} />
      </div>
      <div class="" style={{ "margin-left": "16px" }}>
        <div  class={`w100 ${css.layer_propiedades} py-10 px-12`}>
          <div class="w100 mb-08">Parámetros SMTP para notificaciones</div>
          <div class="w100-10 flex-wrap">
            <Input css="w-12x mb-10" inputCss="s3" label="Host" save="host" saveOn={empresa().smtp} />
            <Input css="w-12x mb-10" inputCss="s3" label="Port" save="port" saveOn={empresa().smtp} type="number" />
            <Input css="w-12x mb-10" inputCss="s3" label="Usuario" save="user" saveOn={empresa().smtp} />
            <Input css="w-12x mb-10" inputCss="s3" label="Password" save="pwd" saveOn={empresa().smtp} />
            <Input css="w-24x mb-10" inputCss="s3" label="Email" save="email" saveOn={empresa().smtp} />
          </div>
        </div>
      </div>
    </div>
  </PageContainer>
}

// frontend/routes/admin/parametros/+page.svelte
<script lang="ts">
import Input from '$components/Input.svelte';
import Page from '$ui/Page.svelte';
import { Notify } from '$core/helpers';
    import pkg from 'notiflix'
const { Loading } = pkg;
  import { EmpresaParametrosService, postEmpresaParametros } from "./empresas.svelte"

  const service = new EmpresaParametrosService()

  async function saveEmpresa() {
    const form = service.empresa
    if((form.RUC||"").length === 0 || (form.Nombre||"").length === 0 ||
      (form.RazonSocial||"").length === 0 || (form.Email||"").length === 0 ){
      Notify.failure("Faltan datos a guardar.")
      return
    }

    Loading.standard("Guardando...")
    try {
      await postEmpresaParametros(form)
      Notify.success("Datos guardados correctamente")
    } catch (error) {
      // Error handled by POST
    }
    Loading.remove()
  }
</script>

<Page title="Parámetros">
    <div class="flex justify-between items-center mb-8">
      <div><div class="h3 ff-bold">Parámetros de la Empresa</div></div>
      <div class="flex items-center">
        <button class="bx-blue" onclick={ev => {
          ev.stopPropagation()
          saveEmpresa()
        }}>
          <i class="icon-floppy mr-2"></i>Guardar
        </button>
      </div>
    </div>
    <div class="w-full grid grid-cols-1 lg:grid-cols-[4fr_3fr] gap-4">
      <div class="grid grid-cols-24 gap-10 content-start">
        <Input css="col-span-14" label="Nombre" save="Nombre" bind:saveOn={service.empresa}
          required={true} />
        <Input css="col-span-10" label="RUC" save="RUC" bind:saveOn={service.empresa}
          required={true} />
        <Input css="col-span-14" label="Razón Social" save="RazonSocial"
          bind:saveOn={service.empresa} required={true} />
        <Input css="col-span-10" label="Teléfono" save="Telefono" bind:saveOn={service.empresa} />
        <Input css="col-span-14" label="Correo Electrónico" save="Email"
          bind:saveOn={service.empresa} required={true} />
        <Input css="col-span-10" label="Representante" save="Representante" bind:saveOn={service.empresa} />
        <Input css="col-span-14" label="Dirección Legal" save="Direccion"
          bind:saveOn={service.empresa} />
        <Input css="col-span-10" label="Ciudad" save="Ciudad" bind:saveOn={service.empresa} />

        <div class="col-span-24 mb-2"><div class="h3 ff-bold">Ecommerce</div></div>
        <Input css="col-span-12" label="Llave Pública (Pruebas)"
          save="LlavePubDev" bind:saveOn={service.empresa.CulquiConfig} />
        <Input css="col-span-12" label="Llave Privada (Pruebas)"
          save="LlaveDev" bind:saveOn={service.empresa.CulquiConfig} />
        <Input css="col-span-12" label="Llave Pública (Live)"
          save="LlavePubLive" bind:saveOn={service.empresa.CulquiConfig} />
        <Input css="col-span-12" label="Llave Privada (Live)"
          save="LlaveLive" bind:saveOn={service.empresa.CulquiConfig} />
        <Input css="col-span-12" label="Culqui LLave RSA ID"
          save="RsaKeyID" bind:saveOn={service.empresa.CulquiConfig} />
        <Input css="col-span-12" label="Culqui LLave RSA"
          save="RsaKey" bind:saveOn={service.empresa.CulquiConfig} />
      </div>
      <div class="" style="margin-left: 16px">
        <div class="w-full py-10 px-12 bg-white rounded shadow-sm">
          <div class="w-full mb-8">Parámetros SMTP para notificaciones</div>
          <div class="grid grid-cols-24 gap-4">
            <Input css="col-span-12" label="Host" save="Host" bind:saveOn={service.empresa.SmtpConfig} />
            <Input css="col-span-12" label="Port" save="Port" bind:saveOn={service.empresa.SmtpConfig} type="number" />
            <Input css="col-span-12" label="Usuario" save="User" bind:saveOn={service.empresa.SmtpConfig} />
            <Input css="col-span-12" label="Password" save="Password" bind:saveOn={service.empresa.SmtpConfig} />
            <Input css="col-span-24" label="Email" save="Email" bind:saveOn={service.empresa.SmtpConfig} />
          </div>
        </div>
      </div>
    </div>
</Page>
