// frontend_deprecated/src/components/Input.tsx
import { For, JSX, createEffect, createSignal } from "solid-js";
import { on } from "solid-js";
import s1 from "./components.module.css"

export interface IInput<T> {
  id?: number
  saveOn: T
  save: keyof T
  label?: string
  css?: string
  inputCss?: string
  required?: boolean
  validator?: (v: (string|number)) => boolean
  type?: string
  placeholder?: string
  disabled?: boolean
  onChange?: (() => void)
  postValue?: JSX.Element
  baseDecimals?: number
  content?: (string|JSX.Element)
  transform?: (v: (string|number)) => (string|number)
  useTextArea?: boolean
  rows?: number
}

const [inputUpdater, setInputUpdater] = createSignal(new Map as Map<number,number>)

export const refreshInput = (ids: number[]) => {
  const map = new Map(inputUpdater())
  for(let id of ids){
    const currentValue = map.get(id) || 0
    map.set(id, currentValue + 1)
  }
  setInputUpdater(map)
}

export function Input<T>(props: IInput<T>) {

  const baseDecimals = props.baseDecimals ? 10 ** props.baseDecimals : 0

  const chekIfInputIsValid = (_props: IInput<T>): number => {
    if(!_props.required || _props.disabled){ return 0 }
    if(!_props.saveOn || !_props.save) return 1
    const value = _props.saveOn[_props.save] as (string|number)

    let pass = !props.required
    if(props.validator){
      pass = props.validator(value as (string|number))
    } else {
      if(value || value === 0){ pass = true }
    } 
    return pass ? 2 : 1
  }

  const [inputValue, setInputValue] = createSignal("" as (string|number))
  const [isInputValid, setIsInputValid] = createSignal(chekIfInputIsValid(props))
  
  let isChange = 0

  const onKeyUp = (ev: KeyboardEvent, isBlur?: boolean) => {
    ev.stopPropagation()
    const target = ev.target as HTMLInputElement
    let value = target.value as (number|string)

    if(props.type === 'number'){
      if(!isBlur && !value && ev.key === "-"){ return }
      if(isNaN(value as number)){ value === undefined }
      else {
        value = parseFloat(value as string)
        if(baseDecimals){ value = Math.round(value * baseDecimals)}
      }
    }

    if(props.transform && isBlur){ value = props.transform(value) }

    if(props.saveOn && props.save){
      props.saveOn[props.save] = value as T[keyof T]
      setIsInputValid(chekIfInputIsValid(props))
    }
    setInputValue(value)
  }
  
  createEffect(on(
    () => [props.saveOn, props.id ? inputUpdater().get(props.id)|| 0 : 0], 
    () => {
      const v = props.saveOn[props.save]
      setInputValue(typeof v === 'number' ? v as number : (v as string||""))
      setIsInputValid(chekIfInputIsValid(props))
    }
  ))
  
  let cN = `${s1.input} p-rel`
  if(props.css){ cN += " " + props.css }
  
  const iconValid = () => {
    if(!isInputValid()) return null
    else if(isInputValid() === 2){ return <i class="v-icon icon-ok c-green"></i>  }
    else if(isInputValid() === 1){ 
      return <i class="v-icon icon-attention c-red"></i> 
    }
  }

  const getValue = () => {
    const value = inputValue()
    if(typeof value !== 'number'){ return value || "" }
    return baseDecimals ? (value as number / baseDecimals) : value
  }

  return <div class={cN}>
    { props.label && <>
        <div class={`${s1.input_lab}`}>{props.label}{ iconValid() }</div>
        <div class={`${s1.input_lab1}`}>{props.label}{ iconValid() }</div>
      </>
    }
    <div class={`${s1.input_div} w100`}>
      {
      props.useTextArea ?
      <textarea class={s1.input_inp +" "+ (props.inputCss||"") } 
        value={getValue()} 
        onkeyup={ev => { onKeyUp(ev); isChange++ }}
        placeholder={props.placeholder||""}
        disabled={props.disabled}
        rows={props.rows}
        onBlur={(ev) => {
          onKeyUp(ev as unknown as any, true)
          if(props.onChange && isChange){ 
            props.onChange(); isChange = 0
          }
        }}      
      />
      :
      <input class={s1.input_inp +" "+ (props.inputCss||"") } 
        value={getValue()} 
        onkeyup={ev => { onKeyUp(ev); isChange++ }}
        type={props.type || "text"}
        placeholder={props.placeholder||""}
        disabled={props.disabled}
        onBlur={(ev) => {
          onKeyUp(ev as unknown as any, true)
          if(props.onChange && isChange){ 
            props.onChange(); isChange = 0
          }
        }}
      /> 
      }
      { !props.label && iconValid() }
      { props.postValue || null  }
    </div>
  </div>
}

interface ICheckBoxContainer<T> {
  saveOn: any
  save: string
  options: T[]
  keys: string
  label?: string
  css?: string
  required?: boolean
  onChange?: () => void
}

export function CheckBoxContainer<T>(props: ICheckBoxContainer<T>) {
  const [keyId, keyName] = props.keys.split(".") as [keyof T, keyof T]

  const [optionsSelected, setOptionsSelected] = createSignal([] as (number|string)[])

  createEffect(on(
    () => [props.saveOn], 
    () => { 
      setOptionsSelected([...(props.saveOn[props.save] || [])])
    }
  ))
  
  return <div class={"flex " + (props.css||"")}>
    <For each={props.options}>
      {(opt) => {
          const checked = () =>{
            return optionsSelected().includes(opt[keyId] as (number|string))
          }

          return <div class="checkbox-cnt mr-06 ">
            <div class={"checkbox-s1"+ (checked() ? " checked" : "")} 
              onClick={ev => {
                ev.stopPropagation()
                const id = opt[keyId] as (number|string)
                let newSelected = [...(optionsSelected())]
                if(newSelected.includes(id)){
                  newSelected = newSelected.filter(x => x !== id)
                } else {
                  newSelected.push(id)
                }
                setOptionsSelected(newSelected)
                if(props.saveOn && props.save){
                  props.saveOn[props.save] = newSelected
                }
              }}>
              <i class="icon-ok"></i>
            </div>
            <label>{opt[keyName] as string}</label>
          </div>
        }
      }
    </For>
  </div>
}

interface ICheckBox<T> {
  saveOn?: any
  save?: string
  label?: string
  css?: string
  required?: boolean
  onChange?: (b:boolean) => void
  checked?: boolean
}

export function CheckBox<T>(props: ICheckBox<T>) {
  const [checked, setChecked] = createSignal(false as boolean)

  createEffect(on(
    () => [props.saveOn, props.checked], 
    () => { 
      if(typeof props.checked === 'boolean'){
        setChecked(props.checked)
        return
      }
      if(props.saveOn && props.save){
        setChecked(props.saveOn[props.save] || false)
      }
    }
  ))

  const updateChecked = () =>{
    if(typeof props.checked === 'boolean'){ return }
    if(props.saveOn && props.save){
      props.saveOn[props.save] = checked()
    }
  }
  
  return <div class="checkbox-cnt mr-06 ">
    <div class={"checkbox-s1"+ (checked() ? " checked" : "")} 
      onClick={ev => {
        ev.stopPropagation()
        const newCheched = !checked()
        setChecked(newCheched)
        updateChecked()
        if(props.onChange){ props.onChange(newCheched) }
      }}>
      <i class="icon-ok"></i>
    </div>
    <label>{props.label}</label>
  </div>
}

export interface IInputDisabled<T> {
  label?: string
  css?: string
  inputCss?: string
  content?: (string|JSX.Element)
  getContent?: () => (string|JSX.Element)
  postValue?: JSX.Element
  decimals?: number
}

export function InputDisabled<T>(props: IInputDisabled<T>) {

  const getContent = props.getContent ? props.getContent : () => props.content

  let cN = "in-5c p-rel flex-column a-start"
  if(props.css){ cN += " " + props.css }

  return <div class={cN}>
    { props.label && 
      <div class="mr-auto label">
        {props.label}
      </div>
    }
    <div class={"in-5 flex ai-center " + (props.inputCss||"") }>
      {getContent()}
    </div>
    { props.postValue || null  }
  </div>
}

// frontend2/src/components/Input.svelte
<script lang="ts" generics="T">
    import { untrack } from "svelte";
  import s1 from "./components.module.css";
  import { type Element } from "./micro/Renderer.svelte";

  export interface IInput<T> {
    id?: number;
    saveOn: T;
    save: keyof T;
    label?: string;
    css?: string;
    inputCss?: string;
    required?: boolean;
    validator?: (v: string | number) => boolean;
    type?: string;
    placeholder?: string;
    disabled?: boolean;
    onChange?: () => void;
    postValue?: string | Element[];
    baseDecimals?: number;
    content?: string | any;
    transform?: (v: string | number) => string | number;
    useTextArea?: boolean;
    rows?: number;
  }

  const {
    id,
    saveOn,
    save,
    label,
    css,
    inputCss,
    required,
    validator,
    type,
    placeholder,
    disabled,
    onChange,
    postValue,
    baseDecimals,
    content,
    transform,
    useTextArea,
    rows,
  }: IInput<T> = $props();

  /*
  // Shared reactive state
  let inputUpdater = $state(new Map<number, number>());

  export function refreshInput(ids: number[]) {
    const map = new Map(inputUpdater);
    for (let id of ids) {
      const currentValue = map.get(id) || 0;
      map.set(id, currentValue + 1);
    }
    inputUpdater = map;
  }
  */

  const baseDecimalsValue = baseDecimals ? 10 ** baseDecimals : 0;
  let inputValue = $state("" as string | number);
  let isInputValid = $state(checkIfInputIsValid());
  let isChange = 0;

  function checkIfInputIsValid(): number {
    if (!required || disabled) return 0;
    if (!saveOn || !save) return 1;
    const value = saveOn[save] as string | number;

    let pass = !required;
    if (validator) {
      pass = validator(value);
    } else {
      if (value || value === 0) pass = true;
    }
    return pass ? 2 : 1;
  }

  function onKeyUp(ev: KeyboardEvent | FocusEvent, isBlur?: boolean) {
    ev.stopPropagation();
    const target = ev.target as HTMLInputElement | HTMLTextAreaElement;
    let value: string | number = target.value;

    if (type === "number") {
      if (!isBlur && !value && (ev as KeyboardEvent).key === "-") return;
      if (isNaN(value as unknown as number)) {
        value = undefined as any;
      } else {
        value = parseFloat(value as string);
        if (baseDecimalsValue) value = Math.round(value * baseDecimalsValue);
      }
    }

    if (transform && isBlur) {
      value = transform(value);
    }

    untrack(() => {
      if (saveOn && save) {
        saveOn[save] = value as any;
        isInputValid = checkIfInputIsValid();
      }
    })

    inputValue = value;
  }

  function iconValid() {
    if (!isInputValid) return null;
    else if (isInputValid === 2)
      return `<i class="v-icon icon-ok c-green"></i>`;
    else if (isInputValid === 1)
      return `<i class="v-icon icon-attention c-red"></i>`;
    return null;
  }

  /*
  $effect(() => {
    const updaterVal = id ? inputUpdater.get(id) || 0 : 0;
    updaterVal; // dependency
    const v = saveOn[save];
    inputValue = typeof v === "number" ? v : (v as string) || "";
    isInputValid = checkIfInputIsValid();
  });
  */

  let lastSaveOn: T | undefined

  $effect(() => {
    if(!saveOn || !save){ return }
    if(lastSaveOn === saveOn){ return }
    lastSaveOn = saveOn

    if(saveOn[save] !== inputValue){
      untrack(() => {
        const v = saveOn[save]
        inputValue = typeof v === "number" ? v : (v as string) || ""
        isInputValid = checkIfInputIsValid()
      })
    }
  })

  let cN = $derived(`${s1.input} p-rel` + (css ? " " + css : ""));
</script>

<div class={cN}>
  {#if label}
    <div class={s1.input_lab_cell_left}><div></div></div>
    <div class={s1.input_lab}>
      {label}{@html iconValid() || ""}
    </div>
    <div class={s1.input_lab_cell_right}><div></div></div>
  {/if}
  <div class={s1.input_shadow_layer}>
    <div></div>
  </div>
  <div class={`${s1.input_div} flex w-full`}>
    <div class={s1.input_div_1}>
      <div></div>
    </div>
    {#if useTextArea}
      <textarea
        class={`w-full ${s1.input_inp} ${inputCss || ""}`}
        bind:value={inputValue}
        placeholder={placeholder || ""}
        {disabled}
        {rows}
        onkeyup={(ev) => {
          onKeyUp(ev);
          isChange++;
        }}
        onblur={(ev) => {
          console.log("input saveon:",$state.snapshot(saveOn))
          onKeyUp(ev, true);
          if (onChange && isChange) {
            onChange();
            isChange = 0;
          }
        }}
      ></textarea>
    {:else}
      <input class={`w-full ${s1.input_inp} ${inputCss || ""}`}
        bind:value={inputValue}
        type={type || "text"}
        placeholder={placeholder || ""}
        {disabled}
        onkeyup={(ev) => {
          onKeyUp(ev);
          isChange++;
        }}
        onblur={(ev) => {
          onKeyUp(ev, true);
          if (onChange && isChange) {
            onChange();
            isChange = 0;
          }
        }}
      />
    {/if}

    {#if !label}
      {@html iconValid() || ""}
    {/if}
    {#if postValue}
      {postValue}
    {/if}
  </div>
</div>
