// frontend/src/routes/admin/usuarios.tsx
import { Loading, Notify } from "notiflix"
import { createSignal } from "solid-js"
import { Input } from "~/components/Input"
import { Modal, setOpenModals } from "~/components/Modals"
import { QTable } from "~/components/QTable"
import { SearchCard, SearchSelect } from "~/components/SearchSelect"
import { formatTime, throttle } from "~/core/main"
import { PageContainer } from "~/core/page"
import { IUsuario, postUsuario, useEmpresasAPI, usePerfilesAPI, useUsuariosAPI } from "~/services/admin/empresas"

export default function UsuariosPage() {
  
  const [empresas] = useEmpresasAPI()
  const [usuarios, setUsuarios] = useUsuariosAPI()
  const [perfiles] = usePerfilesAPI()
  const [filterText, setFilterText] = createSignal("")

  const [usuarioForm, setUsuarioForm] = createSignal({} as IUsuario)

  const saveUsuario = async (isDelete?: boolean) => {
    const form = usuarioForm()
    if((form.usuario?.length||0) < 4 || (form.nombres?.length||0) < 4){
      Notify.failure("El usuario y el nombre deben tener al menos 4 caracteres.")
      return
    }
    if(form.password1) form.password1 = form.password1.trim()
    if(form.password2) form.password2 = form.password2.trim()

    if(!form.id || form.password1){
      let err = ""
      if((form.password1.length||0) < 6){
        err = "El password tiene menos de 6 caracteres."
      } else if(form.password1 !== form.password2){
        err = "Los password no coinciden."
      }
      if(err){ Notify.failure(err); return }
    }

    Loading.standard("Creando /Actualizando Usuario...")
    try {
      var result = await postUsuario(form)
    } catch (error) {
      Notify.failure(error as string); Loading.remove(); return
    }

    let usuarios_ = [...usuarios().usuarios]

    if(form.id){
      const selected = usuarios().usuarios.find(x => x.id === form.id)
      if(selected){ Object.assign(selected, form) }
      if(isDelete){ usuarios_ = usuarios_.filter(x => x.id !== form.id) }
    } else {
      form.id = result.id
      usuarios_.unshift(form)
    }
    Loading.remove()
    
    setUsuarios({...usuarios(), usuarios: usuarios_ })
    setOpenModals([])
  }

  return <PageContainer title="Usuarios" fetchLoading={true}>
    <div class="h100">
      <div class="flex ai-center jc-between mb-06">
        <div class="search-c4 mr-16 w16rem">
          <div><i class="icon-search"></i></div>
          <input class="w100" autocomplete="off" type="text" onKeyUp={ev => {
            ev.stopPropagation()
            throttle(() => {
              setFilterText(((ev.target as any).value||"").toLowerCase().trim())
            },150)
          }}/>
        </div>
        <div class="flex ai-center">
          <button class="bn1 b-green" onClick={ev => {
            ev.stopPropagation()
            setUsuarioForm({ ss: 1 } as IUsuario)
            setOpenModals([1])
          }}>
            <i class="icon-plus"></i>
          </button>
        </div>
      </div>
      <QTable data={usuarios()?.usuarios||[]} css="w100"
        maxHeight="calc(80vh - 13rem)" style={{ "height": '100%' }}
        columns={[
          { header: "ID", headerStyle: { width: '3.4rem' }, css: "c",
            getValue: e => e.id
          },
          { header: "Usuario", cardCss: "h3 ff-bold c-purple",
            getValue: e => e.usuario, cardColumn: [1,1]
          },
          { header: "Nombres", cardColumn: [2,1],
            getValue: e => e.nombres +" "+ e.apellidos
          },
          { header: "Email", cardColumn: [3,1], cardCss: "h5 c-steel",
            getValue: e => e.email
          },
          { header: "Estado", cardColumn: [3,2],
            getValue: e => e.ss, cardCss: "h5 c-steel",
          },
          { header: "Actualizado", headerStyle: { width: '9rem' },
            css: 'nowrap',
            getValue: e => formatTime(e.upd,"Y-m-d h:n") as string
          },
          { header: "...", headerStyle: { width: '2.6rem' }, css: "t-c",
            cardColumn: [1,2],
            render: (e,i) => {
              const onclick = (ev: MouseEvent) => {
                ev.stopPropagation()
                setOpenModals([1])
                setUsuarioForm({...e})
              }
              return <button class="bnr2 b-blue b-card-1" onClick={onclick}>
                <i class="icon-pencil"></i>
              </button>
            }
          }
        ]}    
      />
    </div>
    <Modal id={1} css="w56-78 in-s2"
      title={(usuarioForm()?.id > 0 ? "Actualizar" : "Guardar") + " Usuario"}
      onSave={()=> {
        console.log("usuario a guardar::", usuarioForm())
        saveUsuario()
      }}
      onDelete={()=> {
        saveUsuario(true)
      }}
    >
      <div class="flex-wrap ai-start w100-10">
        <Input saveOn={usuarioForm()} save="usuario" 
          css="w-12x mb-10" label="Usuario" required={true}
          disabled={usuarioForm()?.id > 0}
        />
        <Input saveOn={usuarioForm()} save="nombres" 
          css="w-12x mb-10" label="Nombres" required={true}
        />
        <Input saveOn={usuarioForm()} save="apellidos" 
          css="w-12x mb-10" label="Apellidos"
        />
        <Input saveOn={usuarioForm()} save="documentoNro" 
          css="w-12x mb-10" label="Nº Documento"
        />
        <Input saveOn={usuarioForm()} save="cargo" 
          css="w-12x mb-10" label="Cargo"
        />
        <Input saveOn={usuarioForm()} save="email" 
          css="w-12x mb-10" label="Email"
        />
        <SearchCard saveOn={usuarioForm()} save="perfilesIDs" 
          css="w100 mb-10 ai-start" label="" placeholder="Perfiles"
          options={perfiles().perfiles} keys="id.nombre" inputCss="w-07x"
        />
        <Input saveOn={usuarioForm()} save="password1" 
          css="w-12x mb-10" label="Password" type="password"
          required={!usuarioForm().id}
          placeholder={usuarioForm().id > 0 ? "SIN CAMBIAR" : ""}
        />
        <Input saveOn={usuarioForm()} save="password2" required={!usuarioForm().id}
          css="w-12x mb-10" label="Password (Repetir)" type="password"
        />
      </div>
    </Modal>
  </PageContainer>
}

// frontend/pkg-main/routes/admin/usuarios/+page.svelte
<script lang="ts">
import Input from '$components/Input.svelte';
import Modal from '$components/Modal.svelte';
import Page from '$ui/Page.svelte';
import SearchCard from '$components/SearchCard.svelte';
import VTable from '$components/vTable/VTable.svelte';
import type { ITableColumn } from '$components/vTable/types';
import { Notify, throttle } from '$core/helpers';
import { Core, closeModal } from '$core/store.svelte';
import { formatTime } from '$core/helpers';
  import pkg from 'notiflix'
const { Loading } = pkg
  import { UsuariosService, PerfilesService, postUsuario, type IUsuario } from "./usuarios.svelte"

  const usuariosService = new UsuariosService()
  const perfilesService = new PerfilesService()

  let filterText = $state("")
  let usuarioForm = $state({} as IUsuario)

  async function saveUsuario(isDelete?: boolean) {
    const form = usuarioForm

    if ((form.usuario?.length || 0) < 4 || (form.nombres?.length || 0) < 4) {
      Notify.failure("El usuario y el nombre deben tener al menos 4 caracteres.")
      return
    }

    if (form.password1) form.password1 = form.password1.trim()
    if (form.password2) form.password2 = form.password2.trim()

    if (!form.id || form.password1) {
      let err = ""
      if ((form.password1?.length || 0) < 6) {
        err = "El password tiene menos de 6 caracteres."
      } else if (form.password1 !== form.password2) {
        err = "Los password no coinciden."
      }
      if (err) {
        Notify.failure(err)
        return
      }
    }

    Loading.standard("Creando/Actualizando Usuario...")
    try {
      const result = await postUsuario(form)

      if (isDelete) {
        usuariosService.removeUsuario(form.id)
      } else {
        if (!form.id) {
          form.id = result.id
        }
        usuariosService.updateUsuario(form)
      }

      closeModal(1)
    } catch (error) {
      Notify.failure(error as string)
    }
    Loading.remove()
  }

  const columns: ITableColumn<IUsuario>[] = [
    {
      header: "ID",
      headerCss: "w-54",
      cellCss: "text-center ff-bold",
      getValue: e => e.id
    },
    {
      header: "Usuario", highlight: true,
      cellCss: "px-6 c-purple",
      getValue: e => e.usuario
    },
    {
      header: "Nombres", highlight: true,
      getValue: e => `${e.nombres} ${e.apellidos||""}`
    },
    {
      header: "Email",
      cellCss: "px-6",
      getValue: e => e.email
    },
    {
      header: "Estado",
      headerCss: "w-80",
      cellCss: "text-center",
      getValue: e => e.ss
    },
    {
      header: "Actualizado",
      headerCss: "w-144",
      cellCss: "px-6 nowrap",
      getValue: e => formatTime(e.upd, "Y-m-d h:n") as string
    },
    {
      header: "...",
      headerCss: "w-42",
      cellCss: "t-c",
      id: "actions",
      buttonEditHandler: (rec) => {
        usuarioForm = { ...rec }
        Core.openModal(1)
      }
    }
  ]
</script>

<Page title="Usuarios">
  <div class="h-full">
    <div class="flex items-center justify-between mb-6">
      <div class="i-search mr-16 w-256">
        <div><i class="icon-search"></i></div>
        <input class="w-full" autocomplete="off" type="text" onkeyup={ev => {
          ev.stopPropagation()
          throttle(() => {
            filterText = ((ev.target as HTMLInputElement).value || "").toLowerCase().trim()
          }, 150)
        }}>
      </div>
      <div class="flex items-center">
        <button class="bx-green" onclick={ev => {
          ev.stopPropagation()
          usuarioForm = { ss: 1 } as IUsuario
          Core.openModal(1)
        }} aria-label="Agregar usuario">
          <i class="icon-plus"></i>
        </button>
      </div>
    </div>

    <VTable
      columns={columns}
      data={usuariosService.usuarios}
      css="w-full"
      maxHeight="calc(80vh - 13rem)"
      filterText={filterText}
      getFilterContent={e => [e.usuario, e.nombres, e.apellidos, e.email].filter(x => x).join(" ").toLowerCase()}
    >
    </VTable>
  </div>

  <Modal
    id={1}
    size={5}
    title={(usuarioForm?.id > 0 ? "Actualizar" : "Guardar") + " Usuario"}
    isEdit={usuarioForm?.id > 0}
    onSave={() => saveUsuario()}
    onDelete={usuarioForm?.id > 0 ? () => saveUsuario(true) : undefined}
  >
    <div class="grid grid-cols-24 gap-10 p-6">
      <Input
        bind:saveOn={usuarioForm}
        save="usuario"
        css="col-span-12"
        label="Usuario"
        required={true}
        disabled={usuarioForm?.id > 0}
      />
      <Input
        bind:saveOn={usuarioForm}
        save="nombres"
        css="col-span-12"
        label="Nombres"
        required={true}
      />
      <Input
        bind:saveOn={usuarioForm}
        save="apellidos"
        css="col-span-12"
        label="Apellidos"
      />
      <Input
        bind:saveOn={usuarioForm}
        save="documentoNro"
        css="col-span-12"
        label="Nº Documento"
      />
      <Input
        bind:saveOn={usuarioForm}
        save="cargo"
        css="col-span-12"
        label="Cargo"
      />
      <Input
        bind:saveOn={usuarioForm}
        save="email"
        css="col-span-12"
        label="Email"
      />
      <SearchCard
        bind:saveOn={usuarioForm}
        save="perfilesIDs"
        css="col-span-24"
        options={perfilesService.perfiles}
        keyId="id"
        keyName="nombre"
        label="PERFILES ::"
      />
      <Input
        bind:saveOn={usuarioForm}
        save="password1"
        css="col-span-12"
        label="Password"
        type="password"
        required={!usuarioForm.id}
        placeholder={usuarioForm.id > 0 ? "SIN CAMBIAR" : ""}
      />
      <Input
        bind:saveOn={usuarioForm}
        save="password2"
        css="col-span-12"
        label="Password (Repetir)"
        type="password"
        required={!usuarioForm.id}
      />
    </div>
  </Modal>
</Page>
