// frontend2/src/routes/operaciones/ventas/+page.svelte
<script lang="ts">
  import Input from "$components/Input.svelte";
    import LayerStatic from "$components/micro/LayerStatic.svelte";
  import Page from "$components/Page.svelte";
  import SearchSelect from "$components/SearchSelect.svelte";
  import { Loading, include } from "$lib/helpers";
  import { formatN } from "$shared/main";
  import type { IProductoStock } from "../productos-stock/productos-stock.svelte";
  import { getProductosStock } from "../productos-stock/productos-stock.svelte";
  import { ProductosService } from "../productos/productos.svelte";
  import type { IAlmacen } from "../sedes-almacenes/sedes-almacenes.svelte";
  import { AlmacenesService } from "../sedes-almacenes/sedes-almacenes.svelte";
  import ProductoVentaCard from "./components/ProductoVentaCard.svelte";
  import type { ProductoVenta } from "./ventas.svelte";
  import { VentasState } from "./ventas.svelte";

  // Helpers
  const formatMo = (n: number) => formatN(n, 2);

  // Services
  const almacenesService = new AlmacenesService();
  const productosService = new ProductosService();

  // State
  const ventasState = new VentasState();

  let almacenSelected = $state(-1);
  let productoSelected = $state(-1);
  let searchInput: HTMLInputElement;

  // Data
  let productosStock = $state([] as IProductoStock[]);
  let productosParsed = $state([] as ProductoVenta[]);
  let productosParsedAll = $state([] as ProductoVenta[]); // cache for filtering

  // Effects
  $effect(() => {
    // Auto-select first almacen
    if (almacenSelected === -1 && almacenesService.Almacenes.length > 0) {
      almacenSelected = almacenesService.Almacenes[0].ID;
      loadStock(almacenSelected);
    }
  });

  async function loadStock(almacenID: number) {
    Loading.standard("Cargando stock...");
    productosStock = await getProductosStock(almacenID);
    parseProductos();
    Loading.remove();
  }

  function parseProductos() {
    if (!productosService.productos.length || !productosStock.length) return;

    const productoToStockMap = new Map<number, IProductoStock[]>();
    for (const s of productosStock) {
      const list = productoToStockMap.get(s.ProductoID) || [];
      list.push(s);
      productoToStockMap.set(s.ProductoID, list);
    }

    const newProductos: ProductoVenta[] = [];

    for (const producto of productosService.productos) {
      const stocks = productoToStockMap.get(producto.ID) || [];
      if (stocks.length === 0) continue;

      const base: ProductoVenta = {
        producto: producto,
        cant: 0,
        key: `P${producto.ID}`,
        searchText: producto.Nombre.toLowerCase(),
      };

      const skusStock: IProductoStock[] = [];
      const mainStock: IProductoStock[] = [];

      for (const e of stocks) {
        e.SKU ? skusStock.push(e) : mainStock.push(e);
      }

      // SKU entries
      if (skusStock.length > 0) {
        const clone = { ...base, skus: skusStock, key: `K${producto.ID}` };
        for (const e of skusStock) clone.cant += e.Cantidad;
        newProductos.push(clone);
      }

      // Main entries & Sub-units
      if (mainStock.length > 0) {
        let clone: ProductoVenta | undefined;
        if ((producto.SbnCantidad || 0) > 1) {
          clone = {
            ...base,
            key: `S${producto.ID}`,
            isSubUnidad: true,
            cant: producto.SbnCantidad!,
          };
          // Recalculate generic quantity for sub-units?
          // Legacy: `clone.cant = producto.SbnCantidad` (Logic seems to be per unit or just flagging?)
          // Legacy logic sets cant to `SbnCantidad`. Let's stick to it.
        }

        for (const e of mainStock) base.cant += e.Cantidad;
        newProductos.push(base);

        if (clone) newProductos.push(clone);
      }
    }

    productosParsedAll = newProductos;
    filterProductos(ventasState.filterText);
  }

  let filterTimeout: any;
  function filterProductos(text: string) {
    ventasState.filterText = text;
    // Debounce logic if needed, or simple filter
    if (!text) {
      productosParsed = productosParsedAll;
      return;
    }

    const terms = text.toLowerCase().split(" ");
    productosParsed = productosParsedAll.filter((e) =>
      include(e.searchText, terms),
    );
    productoSelected = -1;
  }

  function handleKeydown(ev: KeyboardEvent) {
    if (ventasState.ventaErrorMessage) ventasState.ventaErrorMessage = "";

    if (ev.key === "ArrowUp") {
      ev.preventDefault();
      const newIdx = productoSelected - 1;
      if (newIdx >= -1) productoSelected = newIdx;
    } else if (ev.key === "ArrowDown") {
      ev.preventDefault();
      const newIdx = productoSelected + 1;
      if (newIdx < productosParsed.length) productoSelected = newIdx;
    } else if (ev.key === "Enter" && productoSelected >= 0) {
      ev.preventDefault();
      // Add 1 unit of selected
      const prod = productosParsed[productoSelected];
      if (prod.skus?.length) {
        ventasState.ventaErrorMessage = "Seleccione un SKU específico.";
        return;
      }
      ventasState.addProducto(prod, 1);
    } else if (ev.key === "Escape") {
      productoSelected = -1;
      searchInput?.focus();
    }
  }
</script>

<svelte:window onkeydown={handleKeydown} />

<Page title="Ventas" sideLayerSize={400}>
  <div class="flex h-full gap-16">
    <!-- Main Content -->
    <div class="flex-1 flex flex-col min-w-0">
      <!-- Toolbar -->
      <div class="flex mb-12">
        <div class="w-250 mr-12">
          <SearchSelect
            label=""
            keyId="ID"
            keyName="Nombre"
            options={almacenesService.Almacenes}
            placeholder="ALMACÉN"
            selected={almacenSelected}
            onChange={(e: IAlmacen) => {
              if (e) {
                almacenSelected = e.ID;
                loadStock(e.ID);
              }
            }}
          />
        </div>

        <div class="flex-1 relative">
          <i
            class="icon-search absolute left-12 top-1/2 -translate-y-1/2 text-gray-400"
          ></i>
          <input
            bind:this={searchInput}
            type="text"
            class="w-full pl-36 pr-16 py-8 bg-gray-50 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 transition-all"
            placeholder="Buscar producto..."
            value={ventasState.filterText}
            oninput={(e) => filterProductos(e.currentTarget.value)}
          />
        </div>
      </div>

      <!-- Grid/List -->
      <div class="flex-1 overflow-y-auto pr-8">
        {#each productosParsed as item, idx (item.key)}
          <ProductoVentaCard
            {idx}
            productoStock={item}
            isSelected={idx === productoSelected}
            ventaProducto={ventasState.ventaProductosMap.get(item.key)}
            filterText={ventasState.filterText}
            onselect={(i) => (productoSelected = i)}
            onmouseover={() => (productoSelected = -1)}
            onadd={(n, sku) => ventasState.addProducto(item, n, sku)}
          />
        {/each}

        {#if productosParsed.length === 0}
          <div class="text-center py-48 text-gray-400">
            No se encontraron productos
          </div>
        {/if}
      </div>
    </div>

    <!-- Side Cart -->
    <div class="w-[38%] min-w-350 ml-24"></div>
    <LayerStatic css="w-[38%] min-w-350 bg-white border-l border-gray-200 flex flex-col h-[calc(100vh-60px)] shadow-lg">
      <!-- Error Message -->
      {#if ventasState.ventaErrorMessage}
        <div class="bg-red-50 m-8 text-red-600 p-12 text-sm font-medium border-b border-red-100 animate-in slide-in-from-top-2"
        >
          {ventasState.ventaErrorMessage}
        </div>
      {/if}
      <!-- Header -->
      <div class="px-16 py-12 border-b border-gray-100 flex items-center justify-between bg-gray-50/50"
      >
        <h3 class="font-bold text-gray-800">DETALLE DE VENTA</h3>
        <button
          class="bg-blue-600 hover:bg-blue-700 text-white px-16 py-6 rounded-lg text-sm font-medium transition-colors flex items-center gap-8 shadow-sm"
          title="Guardar venta"
        >
          Guardar
          <i class="icon-floppy"></i>
        </button>
      </div>

      <!-- Summary -->
      <div
        class="p-16 grid grid-cols-2 gap-16 border-b border-gray-100 bg-white"
      >
        <div class="col-span-2">
          <Input
            label="Cliente"
            css="w-full"
            saveOn={ventasState.form}
            save="clienteID"
          />
        </div>

        <div class="bg-gray-50 p-8 rounded border border-gray-100">
          <div class="text-xs text-gray-500 mb-4">Sub Total</div>
          <div class="font-mono text-gray-800 font-medium">
            {formatMo(ventasState.form.subtotal)}
          </div>
        </div>

        <div class="bg-blue-50 p-8 rounded border border-blue-100">
          <div class="text-xs text-blue-600 mb-4 font-bold">Total</div>
          <div class="font-mono text-blue-700 font-bold text-lg">
            {formatMo(ventasState.form.total)}
          </div>
        </div>
      </div>

      <!-- List -->
      <div class="flex-1 overflow-y-auto p-8 space-y-8">
        {#each ventasState.ventaProductos as item (item.key)}
          <div
            class="flex items-start gap-8 p-8 rounded-lg bg-gray-50 hover:bg-white hover:shadow-sm border border-transparent hover:border-gray-200 transition-all group"
          >
            <div class="text-xs font-bold text-gray-400 pt-4 w-16">
              {ventasState.ventaProductos.indexOf(item) + 1}
            </div>
            <div class="flex-1 min-w-0">
              <div class="text-sm font-medium text-gray-800 truncate">
                {item.producto?.Nombre}
                {#if item.isSubUnidad}
                  <span class="text-purple-600 text-xs ml-4"
                    >({item.producto?.SbnUnidad})</span
                  >
                {/if}
              </div>
              {#if item.skus && item.skus.size > 0}
                <div class="flex flex-wrap gap-4 mt-4">
                  {#each item.skus.entries() as [sku, qty]}
                    <span
                      class="text-[10px] bg-white border border-gray-200 px-6 rounded text-gray-600"
                    >
                      {sku} <span class="font-bold text-gray-800">x{qty}</span>
                    </span>
                  {/each}
                </div>
              {/if}
            </div>

            <div class="text-right">
              <div class="font-mono text-sm font-bold text-gray-700">
                {item.cantidad}
              </div>
              <button
                class="text-red-400 hover:text-red-600 p-4 opacity-0 group-hover:opacity-100 transition-opacity"
                onclick={() => ventasState.removeProducto(item.key)}
                title="Eliminar"
              >
                <i class="icon-trash"></i>
              </button>
            </div>
          </div>
        {/each}

        {#if ventasState.ventaProductos.length === 0}
          <div
            class="flex flex-col items-center justify-center h-192 text-gray-300 gap-8"
          >
            <i class="icon-cart text-4xl"></i>
            <span class="text-sm">Carrito vacío</span>
          </div>
        {/if}
      </div>
    </LayerStatic>
  </div>
</Page>

// frontend/src/routes/comercial/ventas.tsx
import { For, Show, createEffect, createMemo, createSignal, on } from "solid-js";
import { deviceType } from "~/app";
import { CardsList } from "~/components/Cards";
import { SearchSelect, makeHighlString } from "~/components/SearchSelect";
import { Loading, include, throttle } from "~/core/main";
import { PageContainer } from "~/core/page";
import { IProducto, IProductoStock, getProductosStock, useProductosAPI } from "~/services/operaciones/productos";
import { useSedesAlmacenesAPI } from "~/services/operaciones/sedes-almacenes";
import { arrayToMapG, arrayToMapN, arrayToMapS, formatMo, formatN, joinb } from "~/shared/main";
import { Params } from "~/shared/security";
import style from "./ventas.module.css";
import { CheckBox, Input, InputDisabled } from "~/components/Input";
import { QTable } from "~/components/QTable";

export interface ProductoVenta {
  key: string
  cant: number
  producto: IProducto
  searchText: string
  isSubUnidad?: boolean
  skus?: IProductoStock[]
}

export interface SkuCant {
  sku: string, cant: number
}

export interface VentaProducto {
  key: string
  productoID: number
  skus?: Map<string,number>
  lote?: string
  cantidad: number
  isSubUnidad?: boolean
}

export interface IVenta {
  clienteID: number
  subtotal: number
  igv: number
  total: number
}

const [ventaProductoInput, setVentaProductoInput] = createSignal(null as HTMLInputElement)

export default function Ventas() {

  const [productosStock, setProductosStock] = createSignal([] as IProductoStock[])
  const [productos] = useProductosAPI()
  const [almacenes] = useSedesAlmacenesAPI()
  const [form, setForm] = createSignal({ } as IVenta)
  const [filterText, setFilterText] = createSignal("")
  const [productoSelected, setProductoSelected] = createSignal(-1)
  const [almacenSelected, setAlmacenSelected] = createSignal(-1)
  const [ventaErrorMessage, setVentaErrorMessage] = createSignal("")
  const [ventaProductos, setVentaProductos] = createSignal([] as VentaProducto[])

  let searchInput: HTMLInputElement

  const ventaProductosMap = createMemo(() => {
    return arrayToMapS(ventaProductos(), "key")
  })

  const getStock = async (almacenID: number) => {
    let stock: IProductoStock[] = []
    Loading.standard("Obteniendo Registros...")
    try {
      stock = await getProductosStock(almacenID) 
    } catch (error) {
      Loading.remove(); return
    }
    console.log("productos stock::", stock)
    setProductosStock(stock)
    Params.setValue("almacen_id", almacenID)
    Loading.remove(); return
  }

  createEffect(() => {
    if(almacenSelected() == -1 && almacenes()?.Almacenes?.length > 0){
      const form_ = form()
      let almacenID = Params.getValueInt("almacen_id") || 0
      if(!almacenID){ almacenID = almacenes().Almacenes[0].ID }
      setAlmacenSelected(almacenID)
      getStock(almacenID)
    }
  })

  const [productosParsed, setProdustosParsed] = createSignal([] as ProductoVenta[])
  const [productosParsedAll, setProductosParsedAll] = createSignal([] as ProductoVenta[])

  createEffect(() => {    
    const productoToStockMap = arrayToMapG(productosStock(), "ProductoID")
    console.log("productos stock map::", productosStock(), productoToStockMap)
    const newProductos: ProductoVenta[] = []

    for(let producto of productos()?.productos||[]){
      const stocks = productoToStockMap.get(producto.ID) || []
      if(stocks.length === 0){ continue }

      const base = { 
        producto: producto, cant: 0,  key: `P${producto.ID}`,
        searchText: producto.Nombre.toLowerCase()
      } as ProductoVenta

      const skusStock: IProductoStock[] = []
      const mainStock: IProductoStock[] = []

      for(let e of stocks){
        e.SKU ? skusStock.push(e) : mainStock.push(e)
      }

      if(skusStock.length > 0){
        const clone = {...base, skus: skusStock, key: `K${producto.ID}`}
        for(let e of skusStock){ clone.cant += e.Cantidad }
        newProductos.push(clone)
      }

      if(mainStock.length > 0){
        let clone: ProductoVenta
        if(producto.SbnCantidad > 1){
          clone = {...base, key: `S${producto.ID}`}
          clone.isSubUnidad = true
          clone.cant = producto.SbnCantidad
        }

        for(let e of mainStock){ base.cant += e.Cantidad }
        newProductos.push(base)
        if(clone){ newProductos.push(clone) }
      }
    }
    console.log("productos parsed::", newProductos)
    setProdustosParsed(newProductos) 
    setProductosParsedAll(newProductos)        
  })
  
    
  const letters = "abcdefghijklmnopqrstuvwxyz"
  const numbers = "123456789"
  let lastSearchText = ""

  const filterProductos = (text: string) => {
    if(text === filterText() || text === lastSearchText){ return }
    console.log("buscando:: ", text)
    lastSearchText = text
    throttle(() => {
      const textSlice = text.toLowerCase().split(" ")
      const filtered = []
      for(let e of productosParsedAll()){
        if(include(e.searchText, textSlice)){
          filtered.push(e)
        }
      }
      console.log("filtrados::", filtered)
      setProdustosParsed(filtered)
      setFilterText(text)
      setProductoSelected(-1)
    },80)
  }
  
  const agregarProductoVenta = (e: ProductoVenta, cant: number, sku?: string) => {
    const ventaCant = ventaProductosMap().get(e.key)?.cantidad || 0
    const stock = e.cant - ventaCant
    if(stock < cant){ 
      setVentaErrorMessage(`No hay suficiente stock de "${e.producto.Nombre}" para agregar ${cant} unidades.`)
      return
    }
    
    console.log("producto venta::", e)

    const ventaProducto = ventaProductos().find(x => x.key === e.key)
    if(ventaProducto){
      ventaProducto.cantidad += cant
      if(sku){
        const skuAdded = ventaProducto.skus.get(sku)
        if(skuAdded){
          const stockCant = e.skus.find(x => x.SKU === sku)?.Cantidad || 0
          if(skuAdded >= stockCant){
            setVentaErrorMessage(`El SKU ${sku} del producto "${e.producto.Nombre}" sólo posee ${stockCant} unidad(es).`)
            return
          }
          ventaProducto.skus.set(sku, skuAdded +1)
        } else {
          ventaProducto.skus.set(sku, 1)
        }
      }
    } else {
      ventaProductos().push({ 
        key: e.key, cantidad: cant, productoID: e.producto.ID,
        skus: new Map(sku ? [[sku,1]] : []),
        isSubUnidad: e.isSubUnidad || false
      })
    }
    const newVentaProductos = [...ventaProductos()]
    console.log("venta productos::", newVentaProductos)
    setVentaProductos(newVentaProductos)
    const input = ventaProductoInput()
    if(input){ input.value = "" }
    if(searchInput){ searchInput.value = "" }
    setFilterText("")
    setProdustosParsed([...productosParsedAll()])
    setProductoSelected(-1)
  }

  const recalcVentaTotales = (newVentaProductos: VentaProducto[]) => {
    console.log("recalculando::", newVentaProductos)
    const newForm = {...form(), total: 0, subtotal: 0, igv: 0}

    for(let vp of newVentaProductos){
      const producto = productos().productosMap.get(vp.productoID)
      const monto = producto.PrecioFinal * vp.cantidad
      newForm.total += monto
    }
    newForm.subtotal = Math.floor(newForm.total / 1.18)
    newForm.igv = newForm.total - newForm.subtotal
    setForm(newForm)
  }

  createEffect(on(()=> ventaProductos(), 
    () => {
      recalcVentaTotales(ventaProductos())
    }))

  const layerWidth = 52

  return <PageContainer title="Ventas" class="flex">
    <div class="jc-between mb-06 mr-16" style={{ width: `${100 - layerWidth}%` }}
      classList={{ "column": [2,3].includes(deviceType()) }}
    >
      <div class="flex">
        <SearchSelect css="w16rem s6 mb-02 mr-12"
          label="" keys="ID.Nombre" options={almacenes()?.Almacenes || []}
          placeholder=" ALMACÉN" selected={almacenSelected()}
          onChange={e => {
            setAlmacenSelected(e?.ID || -1)
            if(e){ getStock(e.ID); return }
          }}
        />
        <div class="search-c4 mr-16 w14rem">
          <div><i class="icon-search"></i></div>
          <input class="w100" autocomplete="off" type="text" ref={searchInput}
            onKeyUp={ev => {
              ev.stopPropagation()
              const text = ((ev.target as any).value||"").toLowerCase().trim()
              filterProductos(text)
            }}
            onkeypress={() => {
              return false
            }}
            onkeydown={ev => {
              ev.stopPropagation()
              if(ventaErrorMessage()?.length > 0){
                setVentaErrorMessage("")
              }
              console.log(ev.key)
              
              if(ev.key === 'ArrowUp'){
                const newIdx = productoSelected()-1
                if(newIdx < -1){ return }
                setProductoSelected(newIdx)
              } else if(ev.key === 'ArrowDown'){
                setProductoSelected(productoSelected()+1)
              } else if(ev.key === 'Enter' && productoSelected() >= 0){
                const input = ventaProductoInput()
                const cant = parseInt(input.value||"0") || 1
                const producto = productosParsed()[productoSelected()]
                if(producto.skus?.length > 0){
                  setVentaErrorMessage("Debe seleccionar 1 SKU.")
                  return
                }
                agregarProductoVenta(producto, cant)
              } else {
                const key = ev.key.toLocaleLowerCase()
                if(productoSelected() >= 0 && (numbers.includes(key) || ev.key === 'Backspace')){
                  // Cambia el valor del input del element
                  const input = ventaProductoInput()
                  console.log("key backspace:: ", input.value)
                  if(input){
                    if(ev.key === 'Backspace'){
                      if(input.value){
                        input.value = ""
                        ev.preventDefault()
                      }
                    } else {
                      input.value += key
                      ev.preventDefault()
                    }
                  }
                } else if(letters.includes(key) || numbers.includes(key)){
                  filterProductos(lastSearchText + ev.key)
                }
              }
            }}
          />
        </div>
      </div>
      <div class="flex jc-between w100">
        <div class="mr-auto"></div>
        <CheckBox label="Buscar SKU"></CheckBox>
      </div>
      <div style={{ height: 'calc(100% - 12px - 4.2rem)', position: 'relative' }}>
        <CardsList data={productosParsed()}
          render={(e,i) => {
            console.log("card rerender:: ", i, e)
            const isSelected = () => { return i === productoSelected() }
            return <ProductoVentaCard idx={i}
              isSelected={isSelected()} ventasProductosMap={ventaProductosMap()}
              productoStock={e}
              agregarProductoVenta={(cant, sku) => {
                agregarProductoVenta(e, cant, sku)
              }}
              setProductoSelected={setProductoSelected}
              filterText={filterText()}
              onmouseover={() => {
                if(productoSelected() >= 0){ setProductoSelected(-1) }
              }}
            />
          }}
        />
      </div>
    </div>
    <div class="side-layer1 grow-1 px-12 py-08" 
      style={{ width: `calc(var(--page-width) * ${layerWidth/100})` }}>
      { ventaErrorMessage() &&
        <div class="box-error-ms mb-08">{ventaErrorMessage()}</div>
      }
      <div class="flex ai-center jc-between w100 mb-12">
        <div class="ff-bold h3 mb-04">
          DETALLE DE VENTA
        </div>
        <div class="flex ai-center">
          <button class="bn1 b-blue">
            Guardar
            <i class="icon-floppy"></i>
          </button>
        </div>
      </div>
      <div class="w100-10 flex-wrap">
        <Input label="Cliente" css="w-06x" saveOn={form()} save="clienteID" />
        <InputDisabled label="Código" css="w-05x" />
        <InputDisabled label="Sub Total" css="ff-mono w-045x" 
          getContent={() => formatMo(form().subtotal)}/>
        <InputDisabled label="IGV" css="ff-mono w-04x" 
          getContent={() => formatMo(form().igv)}/>
        <InputDisabled label="Total" css="ff-mono w-045x" content={form().total}
          getContent={() => formatMo(form().total)}/>
      </div>
      <QTable data={ventaProductos()} 
        css="w100 mt-12 w-page-t" tableCss="w100"
        maxHeight="calc(100vh - 12rem - 12px)"
        columns={[
          { header: "Nº",
            getValue: (e,idx) => {
              return String(idx + 1)
            }
          },
          { header: "Producto",
            render: e => {
              const producto = productos().productosMap.get(e.productoID)
              let nombre = producto?.Nombre || ""
              if(e.isSubUnidad){
                nombre = `${producto.SbnUnidad} de ${nombre}`
              }
              return nombre
            }
          },
          { header: "SKU",
            render: e => {
              console.log("skuss",e)
              if(!e.skus){ return "" }
              return <>
                { [...e.skus].map(([sku,cant]) => {
                    return <div>{sku} {cant > 1 ? <span class="ml-04">({cant})</span> : null}</div>
                  })

                }
              </>
            }
          },
          { header: "Cantidad",
            render: e => {
              return formatN(e.cantidad)
            }
          },
          { header: "Monto", css: "ff-mono t-r",
            render: e => {
              const producto = productos().productosMap.get(e.productoID)
              const monto = producto.PrecioFinal * e.cantidad
              return <span>
                {formatN(monto/100,2) as string}
              </span>
            }
          },
          { header: "...", headerStyle: { width: '2rem' }, cellStyle: { padding: '0 4px' },
            render: e => {
              return  <button class="bn1 s5 b-red" onClick={ev => {
                ev.stopPropagation()
                const newVentaProductos = ventaProductos().filter(x => x.key !== e.key)
                setVentaProductos(newVentaProductos)
              }}>
                <i class="icon-trash"></i>
              </button>
            }
          },
        ]}
      />
    </div>
  </PageContainer>
}

interface IProductoCantidad {
  onSelect: (cant: number) => void
}

function ProductoCantidad(props: IProductoCantidad){

  const cantidades = [2,3,4,5,6,8,10,12]

  return <div class={["flex p-rel ai-end h100",style.buttons_cantidad].join(" ")}>
    <For each={cantidades}>
      {e => {
        return <div class={`flex-center ff-bold ${style.button_venta_cantidad}`} 
        onClick={ev => {
          ev.stopPropagation()
          props.onSelect(e)
        }}>
          {e}
        </div>
      }} 
    </For>
  </div>
}

interface IProductoVentaCard {
  idx: number
  productoStock: ProductoVenta
  isSelected: boolean
  filterText: string
  ventasProductosMap: Map<string,VentaProducto>
  setProductoSelected: (e: number) => void
  agregarProductoVenta: (cant: number, sku?: string) => void
  onmouseover: () => void
}

const ProductoVentaCard = (props: IProductoVentaCard) => {

  let inputRef: HTMLInputElement
  createEffect(on(() => props.isSelected, () => {
    if(props.isSelected){ setVentaProductoInput(inputRef) }
  }))

  const makeNombre = () => {
    const nombre = makeHighlString(props.productoStock.producto.Nombre, props.filterText)
    if(props.productoStock.isSubUnidad || props.productoStock.skus?.length > 0){
      return <div class="flex ai-center">
        {nombre}
        <Show when={props.productoStock.isSubUnidad}>
          <div class="ml-04 mr-04">|</div>
          <div class="ff-bold c-purple2">{props.productoStock.producto.SbnUnidad}</div>
        </Show>
        <Show when={!props.productoStock.isSubUnidad}>
          <div class="ff-bold ml-04 c-purple2">(SKU)</div>
        </Show>
      </div> 
    } else {
      return nombre
    }
  }

  const isSku = () => props.productoStock.skus?.length > 0
  const getCant = createMemo(() => {    
    const key = props.productoStock.key
    let ventaCant = props.ventasProductosMap.get(key)?.cantidad || 0
    // revisa si hay sub-unidades agregadas
    if(key[0] === 'P'){
      const keySub = `S${key.slice(1)}`
      const subUnidadCant = props.ventasProductosMap.get(keySub)?.cantidad || 0
      if(subUnidadCant > 0){
        const producto = props.productoStock.producto
        ventaCant = ventaCant + Math.ceil(subUnidadCant / producto.SbnCantidad)
      }
    }
    return props.productoStock.cant - ventaCant
  })

  const firstSkus = createMemo(() => {
    let skus = props.productoStock.skus || []
    const ventaProducto = props.ventasProductosMap.get(props.productoStock.key)
    if(ventaProducto?.skus?.size > 0){
      skus = skus.filter(x => {
        if(!ventaProducto.skus.has(x.SKU)){
          return true
        }
        return x.Cantidad > ventaProducto.skus.get(x.SKU)
      })
    }
    if(skus.length > 4){ skus = skus.slice(0,4) }
    return skus
  })

  return <div class={"px-04 py-02"}
    classList={{ "sld": props.isSelected, "sku": isSku() }}
    style={{ "margin-top": props.idx === 0 ? '8px' : undefined }}
    onmouseover={ev => {
      ev.stopPropagation()
      props.onmouseover()
    }}
  >
    <div class={joinb("flex p-rel jc-between", style.card_venta)}
      onClick={() => {
        props.setProductoSelected(props.idx)
      }}
    >
      <div class={style.card_venta_nombre}>
        <div class={style.card_venta_nombre_line}></div>
          { makeNombre() }
      </div>
      <div class="w100 grid ai-center"
        style={{ "grid-template-columns": '1fr 3.8rem 2.8rem 5rem' }}>                  
        <div class={`h100 ${style.card_venta_producto_ctn}`}
            classList={{ "flex ai-center": !isSku() }}
          >
          <div class={`${style.card_venta_producto}`}>
            { makeNombre() }
          </div>
          <Show when={isSku()}>
            <div class="flex-wrap z20 p-rel" style={{ margin: '0 -3px' }}>
              <For each={firstSkus()}>
              {e => {
                return <div class={`h5 ${style.producto_sku}`} onClick={ev =>{
                  ev.stopPropagation()
                  props.agregarProductoVenta(1,e.SKU)
                }}>
                  {e.SKU}
                </div>
              }}
              </For>
            </div>
          </Show>
          <Show when={!isSku()}>
            <ProductoCantidad onSelect={cant => {
              props.agregarProductoVenta(cant)
            }}/>
          </Show>           
        </div>
        <div class={joinb("p-rel flex ai-center",style.input_cantidad)}>
          <input type="number" value="" ref={inputRef}
            class="ff-mono w100"
          />
          <div class="ml-04">/</div>
        </div>
        <div class="ff-mono t-r">{getCant()}</div>
        <div class="ff-mono t-r">
          {formatN(props.productoStock.producto.PrecioFinal/100,2) as string}
        </div>
      </div>
    </div>
  </div>
}
